### ISSUE TITLE
Nifty causing crash in Slick due to mouse wheel moving

### ISSUE THREAD

**Issue by HariboTer** [nifty-gui/nifty-gui#101]
So again I stumbled upon an issue of which I don't know if it's just me or the Nifty library itself.
In my NiftyOverlayBasicGameState, I initialize Nifty as follows:
public class WrapperState extends NiftyOverlayBasicGameState
{
    ....
    @Override
    protected void initGameAndGUI(GameContainer gc, StateBasedGame sbg) throws SlickException
    {
        initNifty(gc, sbg, new SlickRenderDevice(gc), new SlickSoundDevice(), new SlickSlickInputSystem(new PlainSlickInputSystem()), new LWJGLTimeProvider());
        ...
    }

```
@Override
protected void prepareNifty(Nifty nifty, StateBasedGame sbg)
{
    nifty.setLocale(LangData.getLocale());
    java.util.logging.Logger.getAnonymousLogger().getParent().setLevel(java.util.logging.Level.SEVERE);
    java.util.logging.Logger.getLogger("de.lessvoid.nifty.*").setLevel(java.util.logging.Level.SEVERE);
    nifty.getResourceLoader().addResourceLocation(new SchnullerResourceLocation());
    nifty.fromXml(GameData.NIFTY_XML, "null");
}
....
```

}
As far as I know, this is the usual way to get Nifty started and xml parsing, screen switching and rendering etc. works fine, key and mouse input function too - except of the mousewheel, whose movements let Nifty cause a crash:

java.lang.IllegalStateException: Can't generate mouse wheel events without a reference to the Input
    at de.lessvoid.nifty.slick2d.input.AbstractSlickInputSystem.mouseWheelMoved(AbstractSlickInputSystem.java:171)
    at de.lessvoid.nifty.slick2d.input.events.MouseEventWheelMoved.sendToSlick(MouseEventWheelMoved.java:42)
    at de.lessvoid.nifty.slick2d.input.SlickSlickInputSystem.handleInputEvent(SlickSlickInputSystem.java:36)
    at de.lessvoid.nifty.slick2d.input.AbstractSlickInputSystem.forwardEvents(AbstractSlickInputSystem.java:85)
    at de.lessvoid.nifty.Nifty.update(Nifty.java:287)
    at de.lessvoid.nifty.slick2d.NiftyOverlayBasicGameState.update(NiftyOverlayBasicGameState.java:213)
    at org.newdawn.slick.state.StateBasedGame.update(StateBasedGame.java:268)
    at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:657)
    at org.newdawn.slick.AppGameContainer.gameLoop(AppGameContainer.java:408)
    at org.newdawn.slick.AppGameContainer.start(AppGameContainer.java:318)
    at main.StartFrame.actionPerformed(StartFrame.java:289)
    at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
    at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
    at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
    at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
    at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
    at java.awt.Component.processMouseEvent(Unknown Source)
    at javax.swing.JComponent.processMouseEvent(Unknown Source)
    at java.awt.Component.processEvent(Unknown Source)
    at java.awt.Container.processEvent(Unknown Source)
    at java.awt.Component.dispatchEventImpl(Unknown Source)
    at java.awt.Container.dispatchEventImpl(Unknown Source)
    at java.awt.Component.dispatchEvent(Unknown Source)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
    at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
    at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
    at java.awt.Container.dispatchEventImpl(Unknown Source)
    at java.awt.Window.dispatchEventImpl(Unknown Source)
    at java.awt.Component.dispatchEvent(Unknown Source)
    at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
    at java.awt.EventQueue.access$000(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
    at java.awt.EventQueue$4.run(Unknown Source)
    at java.awt.EventQueue$4.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
    at java.awt.EventQueue.dispatchEvent(Unknown Source)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.run(Unknown Source)

As the reason for this exception is out of my knowledge, I would be happy to be told what I did wrong here (or, otherwise, when the fix is coming :P )

**Comment by HariboTer** [comment]
Ok, I switched to initializing Nifty with the parameters
initNifty(gc, sbg, new SlickRenderDevice(gc), new SlickSoundDevice(), new PlainSlickInputSystem(), new LWJGLTimeProvider());
, which got me around the mouse wheel crash. As the error-prone line is to be found in any nifty-with-slick2d online resource, the original error cause still seems worth finding to me ...

**Comment by mkaring** [comment]
The problem is very simple and as you noticed already its all about  the `new SlickSlickInputSystem(new PlainSlickInputSystem())` entry.
The three input systems that are provided by the Slick2D renderer (`NiftySlickInputSystem`, `SlickSlickInputSystem` and `PlainSlickInputSystem`) are only meant to be used as top-level input system and must not be stacked into each other. These input systems all send their input events first to the Nifty-GUI then to your game (with exception of the `PlainSlickInputSystem`, this one does send the events only to the Nifty-GUI).

So in any case you should only use one of those systems and a additional input handling class in case you need to process the events that were not handled by the GUI.
