### ISSUE TITLE
Nifty crashes when selecting text after pasting newline character into a textfield

### ISSUE THREAD

**Issue by ghost** [nifty-gui/nifty-gui#112]
## Expected behavior:

Pasting newlines (i.e., multiple lines of text) into a textfield should replace the newlines with spaces and display the resulting text in one long line. Selection of said text should work normally.
## Actual behavior:

Pasting newlines (i.e., multiple lines of text) into a textfield preserves the newlines, causing the text to be rendered outside of the textfield (if enough lines are pasted), and causes selection of said text to crash nifty gui.
## Steps to reproduce:
1. Run either the default controls or standard examples web start for nifty gui 1.3.2.
2. Go to the textfield demonstration.
3. Paste a newline character into the textfield, or any text including a newline.
4. Notice that if many lines of text are pasted, they will be rendered outside of the textfield.
5. Try and select / highlight any of the text using either shift + arrow or mouse (click + drag).
## System:

Nifty Gui 1.3.2
Java 1.6.0_43
2006 Intel Core 2 Duo MacBook
2 GB RAM
Intel GMA 950 Integrated Graphics Chipset
OS X 10.6.8 Snow Leopard
## Stack Trace:

<pre>
java.lang.StringIndexOutOfBoundsException: String index out of range: 1
    at java.lang.String.substring(String.java:1934)
    at de.lessvoid.nifty.render.NiftyRenderEngineImpl.renderSelectionText(NiftyRenderEngineImpl.java:310)
    at de.lessvoid.nifty.render.NiftyRenderEngineImpl.renderText(NiftyRenderEngineImpl.java:266)
    at de.lessvoid.nifty.elements.render.TextRenderer.renderLine(TextRenderer.java:302)
    at de.lessvoid.nifty.elements.render.TextRenderer.renderLines(TextRenderer.java:201)
    at de.lessvoid.nifty.elements.render.TextRenderer.render(TextRenderer.java:182)
    at de.lessvoid.nifty.elements.Element.renderElement(Element.java:734)
    at de.lessvoid.nifty.elements.Element.render(Element.java:719)
    at de.lessvoid.nifty.elements.Element.renderInternalChildElements(Element.java:751)
    at de.lessvoid.nifty.elements.Element.renderChildren(Element.java:741)
    at de.lessvoid.nifty.elements.Element.render(Element.java:722)
    at de.lessvoid.nifty.elements.Element.renderInternalChildElements(Element.java:751)
    at de.lessvoid.nifty.elements.Element.renderChildren(Element.java:744)
    at de.lessvoid.nifty.elements.Element.render(Element.java:722)
    at de.lessvoid.nifty.elements.Element.renderInternalChildElements(Element.java:751)
    at de.lessvoid.nifty.elements.Element.renderChildren(Element.java:744)
    at de.lessvoid.nifty.elements.Element.render(Element.java:713)
    at de.lessvoid.nifty.elements.Element.renderInternalChildElements(Element.java:751)
    at de.lessvoid.nifty.elements.Element.renderChildren(Element.java:744)
    at de.lessvoid.nifty.elements.Element.render(Element.java:722)
    at de.lessvoid.nifty.elements.Element.renderInternalChildElements(Element.java:751)
    at de.lessvoid.nifty.elements.Element.renderChildren(Element.java:744)
    at de.lessvoid.nifty.elements.Element.render(Element.java:713)
    at de.lessvoid.nifty.elements.Element.renderInternalChildElements(Element.java:751)
    at de.lessvoid.nifty.elements.Element.renderChildren(Element.java:744)
    at de.lessvoid.nifty.elements.Element.render(Element.java:713)
    at de.lessvoid.nifty.elements.Element.renderInternalChildElements(Element.java:751)
    at de.lessvoid.nifty.elements.Element.renderChildren(Element.java:744)
    at de.lessvoid.nifty.elements.Element.render(Element.java:713)
    at de.lessvoid.nifty.screen.Screen.renderLayers(Screen.java:314)
    at de.lessvoid.nifty.Nifty.render(Nifty.java:321)
    at de.lessvoid.nifty.examples.defaultcontrols.LwjglInitHelper.renderLoop(LwjglInitHelper.java:251)
    at de.lessvoid.nifty.examples.defaultcontrols.ControlsDemo.main(ControlsDemo.java:73)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at com.sun.javaws.Launcher.executeApplication(Launcher.java:1927)
    at com.sun.javaws.Launcher.executeMainClass(Launcher.java:1860)
    at com.sun.javaws.Launcher.doLaunchApp(Launcher.java:1622)
    at com.sun.javaws.Launcher.run(Launcher.java:139)
    at java.lang.Thread.run(Thread.java:680)
</pre>

**Comment by void256** [comment]
Thanks for the detailed bug report.

However, this looks a lot like issue #97 which has been fixed in 1.3.3 and 1.4.x.

I'll close the issue now since it really looks like a duplicate issue.

**Comment by ghost** [comment]
Thanks. Not sure how to obtain / use 1.3.3 or 1.4.x. I tried cloning 1.4 from github, but then `mvn clean install` gives: 

[ERROR] Failed to execute goal on project nifty-slick-renderer: Could not resolve dependencies for project lessvoid:nifty-slick-renderer:jar:1.4.0-SNAPSHOT: Failed to collect dependencies for [lessvoid:nifty:jar:1.4.0-SNAPSHOT (compile), slick:slick:jar:274 (compile), junit:junit:jar:4.3.1 (test), org.easymock:easymock:jar:2.4 (test), org.easymock:easymockclassextension:jar:2.4 (test)]: Failed to read artifact descriptor for slick:slick:jar:274: Could not transfer artifact slick:slick:pom:274 from/to slick-maven-repo (http://slick.cokeandcode.com/mavenrepo): Failed to transfer file: http://slick.cokeandcode.com/mavenrepo/slick/slick/274/slick-274.pom. Return code is: 504, ReasonPhrase:Gateway Time-out. -> [Help 1]

Do I need to manually install those artifacts? Do you not get these errors because you're using Nexus or something?
