### ISSUE TITLE
UI from previous state still visible in a Slick2d based game

### ISSUE THREAD

**Issue by DaMitchell** [nifty-gui/nifty-gui#128]
OK I must just be missing a single piece of the puzzle. 

I have my main game class that extends NiftyStateBasedGame which gets passed true for the singleNiftyGuiInstance param. It loads in 2 states the first state just extends NiftyBasicGameState because all its going to do is show some options. Then the second state extends NiftyOverlayBasicGameState because obviously I want the game to display with some UI.

Both states load in a separate xml using the fromXml method in the prepareNifty method.

So in the initial state I have a keyReleased method that when I press enter call game.enterState(GameState.ID). It produces no errors and I can see some stuff logging out to the console so I know game state has loaded correctly but the UI from the initial state has not been cleared.

Is there something I need to be doing when switching states to make sure the UI is cleared?

**Comment by philipwhiuk** [comment]
Do you have a short code sample so we can see what you are doing?

**Comment by void256** [comment]
Yes a code sample will help and I hope @mkaring will magically appear and comment here as well (since he did the new Slick2d integration)

**Comment by DaMitchell** [comment]
Should of put in some example code, just me being lazy :p.

My Client class:

``` java
public class Client extends NiftyStateBasedGame
{
    //....
    public Client(String name)
    {
        super(name, true);
    }

    @Override
    public void initStatesList(GameContainer gameContainer) throws SlickException
    {
        addState(new LoginState());
        addState(new GameState());
    }

    //...
}
```

Login state (state 1):

``` java
public class LoginState extends NiftyBasicGameState
{
    //...

    @Override
    protected void prepareNifty(Nifty nifty, StateBasedGame game)
    {
        nifty.fromXml("res/ui/login.xml", "loginStart");
    }

    public void keyReleased(int key, char c)
    {
        switch(key)
        {
            case Keyboard.KEY_RETURN:
                _game.enterState(GameState.ID); // just to switch state for basic testing
                break;
            default:
                break;
        }
    }

    //...
}
```

Game state (state 2):

``` java
public class GameState extends NiftyOverlayBasicGameState
{
    //...

    @Override
    protected void initGameAndGUI(GameContainer container, StateBasedGame game) throws SlickException
    {
        _mapMatrix = new MapMatrix();
        _mapMatrix.setCurrentMap(0, 0);

        _player = new Player(1);
        _player.setIsCurrent(true);
        _player.setPosition(new Vector2f(288, 480));
        _player.addComponent(new PlayerMovementComponent("player-movement"));
        _player.addComponent(new PlayerRenderComponent("player-render"));

        _mapMatrix.addPlayer(_player);

        initNifty(container, game);
    }

    @Override
    protected void prepareNifty(Nifty nifty, StateBasedGame game)
    {
        nifty.fromXml("res/ui/game.xml", "gameStart");
    }

    //...
}
```

res/ui/login.xml:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<nifty xmlns="http://nifty-gui.sourceforge.net/nifty-1.3.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://nifty-gui.sourceforge.net/nifty-1.3.xsd http://nifty-gui.sourceforge.net/nifty-1.3.xsd">

    <useStyles filename="nifty-default-styles.xml" />
    <useControls filename="nifty-default-controls.xml" />

    <screen id="loginStart" controller="com.dan.mmo.client.ui.LoginStartScreenController">
        <layer id="layer" backgroundColor="#003f" childLayout="center">
            <panel height="25%" width="35%" align="center" valign="center" backgroundColor="#f60f" childLayout="center" visibleToMouse="true">
                <!--<interact onClick="quit()"/>-->
                <effect>
                    <onStartScreen name="move" mode="in" direction="top" length="300" startDelay="0" inherit="true"/>
                    <onEndScreen name="move" mode="out" direction="bottom" length="300" startDelay="0" inherit="true"/>
                    <onHover name="pulsate" scaleFactor="0.008" startColor="#f600" endColor="#ffff" post="true"/>
                </effect>
                <!--<text id="testLabel" font="verdana-small-regular.fnt" text="Hello World!" align="center" valign="center" />-->
                <control id="submitButton" type="button" label="submit!">
                    <interact onClick="submit()" />
                </control>
            </panel>
        </layer>
    </screen>
</nifty>
```

res/ui/game.xml:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<nifty xmlns="http://nifty-gui.sourceforge.net/nifty-1.3.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://nifty-gui.sourceforge.net/nifty-1.3.xsd http://nifty-gui.sourceforge.net/nifty-1.3.xsd">

    <useStyles filename="nifty-default-styles.xml" />
    <useControls filename="nifty-default-controls.xml" />

    <screen id="gameStart" controller="com.dan.mmo.client.ui.GameStartScreenController">
        <layer id="layer" childLayout="center">
            <panel height="25%" width="35%" align="center" valign="center" backgroundColor="#ffff" childLayout="center" visibleToMouse="true">

            </panel>
        </layer>
    </screen>
</nifty>
```

Obviously the class will contain other stuff, like the getID() method, I just include thinks that nifty is touching. I'm also is the game state will work either, mainly because of this error and the two controllers don't contain anything but another way to change into the game state.

Thanks for the reply

**Comment by DaMitchell** [comment]
I think I might have solved it. I have changed from using nifty.fromXml() to using nifty.addXml(). Then in the LoginState I did a super call in the constructor to override the start screen ID and in GameState I did a gotoScreen() call in the enterState() method.

LoginState:

``` java
public class LoginState extends NiftyBasicGameState
{
    //...

    public LoginState()
    {
        super("loginStart");
    }

    @Override
    protected void prepareNifty(Nifty nifty, StateBasedGame game)
    {
        nifty.addXml("res/ui/login.xml");
    }

    //...
}
```

GameState:

``` java
public class GameState extends NiftyOverlayBasicGameState
{
    //...

    @Override
    protected void prepareNifty(Nifty nifty, StateBasedGame game)
    {
        nifty.addXml("res/ui/game.xml");
    }

    @Override
    protected void enterState(GameContainer container, StateBasedGame game) throws SlickException
    {
        getNifty().gotoScreen("gameStart");
    }

    //...
}
```

Hopefully that will help someone if they every experience a similar problem.

If I am missing anything else input is always helpful.

**Comment by mkaring** [comment]
This is exactly correct. You need to switch the Nifty screen yourself when changing in the game state when using the overlay version of the basic game state and you can hand the screen over directly in case you are using the non-overlay version.

The reason for this is mainly that this Slick2D integration uses only one instance of Nifty for all game states. The reason for this it to keep the overhead as low as possible. You can use one Nifty instance per screen if you like by changing the true in the constructor of the NiftyStateBasedGame to false. How ever I do not recommend to try to work around this issue by using multiple Nifty instances. The overhead is not worth it.

**Comment by RyanQuackenbush** [comment]
@mkaring I switched my implementation over from multiple instances to a single one just like @DaMitchell, but keep getting

```
Exception in thread "main" java.lang.NullPointerException
    at org.newdawn.slick.Input.poll(Input.java:1166)
    at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:641)
    at org.newdawn.slick.AppGameContainer.gameLoop(AppGameContainer.java:411)
    at org.newdawn.slick.AppGameContainer.start(AppGameContainer.java:321)
    at core.Game.main(Game.java:94)
```

whenever I attempt to enter the NiftyOverlayGameState. All I have is something like:

```
public class MainMenuState extends NiftyBasicGameState {

    StateBasedGame game;

    @Override
    public int getID() {
        return 0;
    }

    public MainMenuState(){
        super("startMenu");
    }

    @NiftyEventSubscriber(id="home-startGame")
    public void onClick( String id, NiftyMousePrimaryClickedEvent event ){
        game.enterState( 1 ); //1 is the verified gameState id
    }

    @Override
    protected void prepareNifty( Nifty nifty, final StateBasedGame game ) {
        this.game = game;
        nifty.addXml("gui/resources/start.xml");
        nifty.addXml("gui/resources/gameRoom.xml");
        nifty.subscribeAnnotations( this );
    }
}
```

```
public class GameRoomState extends NiftyOverlayGameState {

    private Nifty nifty;
    private Rectangle bg;
    private Color bgColor;
    private Animation waterAnimation;

    public static GameRoom gameRoom;

    @Override
    public int getID() {
        return 2;
    }

    public GameRoomState() throws SlickException{
        System.out.println("Game Room State: Created");
    }

    @Override
    protected void initGameAndGUI( GameContainer container, final StateBasedGame game ) throws SlickException {
        System.out.println("Game Room State: initiatlized");
    }

    @Override
    protected void enterState( GameContainer container, StateBasedGame game ) throws SlickException {
        System.out.println("Screen count: " + getNifty().getAllScreensName().size() );
                for( String s : getNifty().getAllScreensName() ){
            System.out.println("Screen: " + s ); //prints both my startMenu, and gameRoom screen id's
        }
                //errors out without this even implemented
        //getNifty().gotoScreen("gameRoom");
    }

    @Override
    protected void leaveState( GameContainer arg0, StateBasedGame arg1 ) throws SlickException {
    }

    @Override
    protected void prepareNifty( Nifty nifty, final StateBasedGame game ) {
        System.out.println("GameRoomState Prepare nifty");
                //this never is reached
    }
```

The print out is something like 

```
Game Room State: initialized
Screen count: 2
Screen: startMenu
Screen: gameRoom
```

I can verify the multi instance was working before hand ( with Nifty spitting out warnings about using multiple instances. The update and render methods are blank here.
