### ISSUE TITLE
Missing treebox graphics

### ISSUE THREAD

**Issue by AODtorusan** [nifty-gui/nifty-gui#135]
When creating a treebox control and adding any element to the tree results, nifty crashes due to the missing following two images: treebox/closed.png, treebox/opened.png. 

See this stacktrace when using nifty-style-black and nifty-slick-renderer all 1.4.0-SNAPSHOT:

```
Mon Jul 29 12:15:47 CEST 2013 ERROR:Resource not found: treebox/closed.png
java.lang.RuntimeException: Resource not found: treebox/closed.png
    at org.newdawn.slick.util.ResourceLoader.getResourceAsStream(ResourceLoader.java:69)
    at org.newdawn.slick.opengl.InternalTextureLoader.getTexture(InternalTextureLoader.java:273)
    at org.newdawn.slick.Image.<init>(Image.java:270)
    at org.newdawn.slick.Image.<init>(Image.java:244)
    at de.lessvoid.nifty.slick2d.render.image.loader.ImageSlickRenderImageLoader.loadImage(ImageSlickRenderImageLoader.java:22)
    at de.lessvoid.nifty.slick2d.loaders.SlickRenderImageLoaders.loadImage(SlickRenderImageLoaders.java:59)
    at de.lessvoid.nifty.slick2d.render.SlickRenderDevice.createImage(SlickRenderDevice.java:88)
    at de.lessvoid.nifty.render.NiftyImageManager.addImage(NiftyImageManager.java:127)
    at de.lessvoid.nifty.render.NiftyImageManager.registerImage(NiftyImageManager.java:28)
    at de.lessvoid.nifty.render.NiftyRenderEngineImpl.createImage(NiftyRenderEngineImpl.java:172)
    at de.lessvoid.nifty.loaderv2.types.apply.ApplyRendererImage.apply(ApplyRendererImage.java:37)
    at de.lessvoid.nifty.elements.Element.initializeFromAttributes(Element.java:437)
    at de.lessvoid.nifty.loaderv2.types.ElementType.applyAttributes(ElementType.java:227)
    at de.lessvoid.nifty.elements.Element.setStyle(Element.java:2102)
    at de.lessvoid.nifty.controls.treebox.TreeBoxViewConverter.display(TreeBoxViewConverter.java:38)
    at de.lessvoid.nifty.controls.treebox.TreeBoxViewConverter.display(TreeBoxViewConverter.java:23)
    at de.lessvoid.nifty.controls.listbox.ListBoxControl.displayElement(ListBoxControl.java:651)
    at de.lessvoid.nifty.controls.listbox.ListBoxControl.display(ListBoxControl.java:232)
    at de.lessvoid.nifty.controls.listbox.ListBoxImpl.updateView(ListBoxImpl.java:48)
    at de.lessvoid.nifty.controls.listbox.ListBoxImpl.updateView(ListBoxImpl.java:44)
    at de.lessvoid.nifty.controls.listbox.ListBoxControl.bind(ListBoxControl.java:131)
    at de.lessvoid.nifty.controls.treebox.TreeBoxControl.bind(TreeBoxControl.java:64)
    at de.lessvoid.nifty.controls.NiftyInputControl.bindControl(NiftyInputControl.java:121)
    at de.lessvoid.nifty.elements.Element.bindControls(Element.java:2065)
    at de.lessvoid.nifty.elements.Element.bindControls(Element.java:2062)
    at de.lessvoid.nifty.elements.Element.bindControls(Element.java:2062)
    at de.lessvoid.nifty.screen.Screen.bindControls(Screen.java:854)
    at de.lessvoid.nifty.screen.Screen.startScreen(Screen.java:206)
    at de.lessvoid.nifty.Nifty.gotoScreenInternal(Nifty.java:680)
    at de.lessvoid.nifty.Nifty.access$400(Nifty.java:79)
    at de.lessvoid.nifty.Nifty$1.perform(Nifty.java:637)
    at de.lessvoid.nifty.elements.EndOfFrameElementAction.perform(EndOfFrameElementAction.java:22)
    at de.lessvoid.nifty.Nifty.executeEndOfFrameElementActions(Nifty.java:441)
    at de.lessvoid.nifty.Nifty.handleDynamicElements(Nifty.java:360)
    at de.lessvoid.nifty.Nifty.update(Nifty.java:295)
    at de.lessvoid.nifty.slick2d.NiftyOverlayGame.update(NiftyOverlayGame.java:158)
    at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:678)
    at org.newdawn.slick.AppGameContainer.gameLoop(AppGameContainer.java:456)
    at org.newdawn.slick.AppGameContainer.start(AppGameContainer.java:361)
...
```

The controls where made using:

```
<control id="unitTree" name="treeBox" />
```

and populated via:

```
TreeBox<ActorRef> unitTree = mainMenu.findNiftyControl("unitTree", (TreeBox<ActorRef>).class)
unitTree.setTree( buildTree( rootElement ) )
```

Note that the buildTree function returns a `TreeItem<ActorRef>`. 

I assume that all components from nifty-style-black should work out of the box without any user supplied resources?

**Comment by void256** [comment]
Yes! All resources for the standard controls are supposed to be a part of the nifty-style-black jar. This is a bug that needs to be fixed.

Do we still need these pictures @mkaring ? I can't find them in the 1.3 branch so this must be something new in 1.4.

**Comment by mkaring** [comment]
I might have... sort of forgot them :D They should be added to all branches where the treebox is present. I can't remember creating this images for Nifty at any point. So I'll guess you'll have to do new ones.

**Comment by void256** [comment]
Added image resources for the treebox control in 1.4 branch. There are no images being referenced in the 1.3 branch so I've not changed anything there.

![bildschirmfoto 2013-08-11 um 14 37 40](https://f.cloud.github.com/assets/1095704/943940/5d430b80-0283-11e3-9e02-51f3111cf07b.png)
