### ISSUE TITLE
Can't load some images as background image in custom control button

### ISSUE THREAD

**Issue by duindain** [nifty-gui/nifty-gui#142]
I've been writing a custom spinner control in jMonkey with nifty and when i try setting the buttons to increment up or down to a png image created with gimp it errors at runtime

```
SEVERE: Uncaught exception thrown in Thread[LWJGL Renderer Thread,5,main]
java.lang.ArithmeticException: / by zero
    at de.lessvoid.nifty.render.image.areaprovider.SpriteAreaProvider.getSourceArea(SpriteAreaProvider.java:49)
    at de.lessvoid.nifty.render.image.areaprovider.CachedAreaProvider.getSourceArea(CachedAreaProvider.java:28)
    at de.lessvoid.nifty.render.image.CompoundImageMode.render(CompoundImageMode.java:41)
    at de.lessvoid.nifty.render.NiftyImage.render(NiftyImage.java:54)
    at de.lessvoid.nifty.render.NiftyRenderEngineImpl.renderImage(NiftyRenderEngineImpl.java:242)
    at de.lessvoid.nifty.elements.render.ImageRenderer.render(ImageRenderer.java:30)
    at de.lessvoid.nifty.elements.Element.renderElement(Element.java:735)
    at de.lessvoid.nifty.elements.Element.render(Element.java:720)
    at de.lessvoid.nifty.elements.Element.renderInternalChildElements(Element.java:752)
    at de.lessvoid.nifty.elements.Element.renderChildren(Element.java:745)
    at de.lessvoid.nifty.elements.Element.render(Element.java:714)
    at de.lessvoid.nifty.elements.Element.renderInternalChildElements(Element.java:752)
    at de.lessvoid.nifty.elements.Element.renderChildren(Element.java:745)
    at de.lessvoid.nifty.elements.Element.render(Element.java:714)
    at de.lessvoid.nifty.elements.Element.renderInternalChildElements(Element.java:752)
    at de.lessvoid.nifty.elements.Element.renderChildren(Element.java:745)
    at de.lessvoid.nifty.elements.Element.render(Element.java:714)
    at de.lessvoid.nifty.elements.Element.renderInternalChildElements(Element.java:752)
    at de.lessvoid.nifty.elements.Element.renderChildren(Element.java:745)
    at de.lessvoid.nifty.elements.Element.render(Element.java:723)
    at de.lessvoid.nifty.screen.Screen.renderLayers(Screen.java:316)
    at de.lessvoid.nifty.Nifty.render(Nifty.java:322)
    at com.jme3.niftygui.NiftyJmeDisplay.postQueue(NiftyJmeDisplay.java:246)
    at com.jme3.renderer.RenderManager.renderViewPort(RenderManager.java:979)
    at com.jme3.renderer.RenderManager.render(RenderManager.java:1035)
    at com.jme3.app.SimpleApplication.update(SimpleApplication.java:252)
    at com.jme3.system.lwjgl.LwjglAbstractDisplay.runLoop(LwjglAbstractDisplay.java:151)
    at com.jme3.system.lwjgl.LwjglDisplay.runLoop(LwjglDisplay.java:185)
    at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:228)
    at java.lang.Thread.run(Thread.java:722)
```

The images I am using are being found as if i change the path it errors out asset not found they are the correct size for the buttons

If I change the image to another one in the same directory it does render so perhaps this is an issue with the format of the pngs I am using though i did create them all using Gimp with identical settings other than image size and content. I've only left one of the backgroundImage tags in the copied version here.

Anyway at the very least it might be an idea to check and catch the exception if its an image parsing issue and echo that rather than divide by 0 which was not much help in narrowing this down

This is my custom control

```
<controlDefinition name="spinnerselector" controller="Utils.NiftySpinnerSelector">
        <panel childLayout="horizontal" backgroundColor="#8001" height="32px" paddingTop="6px" paddingBottom="6px">
            <control id="spinnerField" name="textfield" style="nifty-textfield" width="50px" height="26px" paddingRight="3px"/>
            <panel childLayout="vertical">
                <control id="spinnerUpButton" backgroundImage="Interface/ButtonBackgroundBlue.png" width="20px" height="13px" name="button">
                    <interact onClick="SpinnerButtonUp()"/>
                </control>
                <control id="spinnerDownButton" width="20px" height="13px" name="button">
                    <interact onClick="SpinnerButtonDown()"/>
                </control>
            </panel>
        </panel>
    </controlDefinition>
```

I am attaching the two test images I am using which will break if set to backgroundImages

![sliderarrowup](https://f.cloud.github.com/assets/4401594/1085729/ba2a7ca2-15de-11e3-9157-b732f48915c4.png)
![sliderarrowdown](https://f.cloud.github.com/assets/4401594/1085730/ba2b3af2-15de-11e3-929c-edc2148b05c5.png)

Cheers thx for making nifty :)

**Comment by void256** [comment]
Well, that's a kinda interesting issue :smile: 

What happens is that the original style of the button control is still being applied by Nifty. You only change the backgroundImage but there are other properties that the default style modifies. For example the "imageMode" property is set to: `... imageMode="sprite-resize:100,23,0,2,96,2,2,2,96,2,19,2,96,2,2"` by the default style.

So Nifty will apply both: your image and this specific sprite-resize imageMode. Which don't match since your image is smaller than the one expected by the imageMode which in the end will lead to the exception :wink: 

What you could do to fix the exception is to reset the imageMode back to its default value using ìmageMode="normal"`on your spinnerUpButton control.

Although this will fix the issue you would end up with a kinda messed up default button mess. The reason for this is that the default style for the button changes other things like the appearance when the button is hovered or focused and so on.

So there are two ways out of this:
1. You don't use the button control at all but instead you'd use a simple image. However you'd lose all of the additional features the button control provides like focus managment and keyboard control and so on.
2. You'd make a copy of the button style and modify it with your own custom images. Then your spinner control would simply be a default button control with your own button style.

For reference here is the current button style which you want to copy and modify to suit your needs. You'd want to call your copy something like ìd="my-spin-button#panel"`and so on.

```
<?xml version="1.0" encoding="UTF-8"?>
<nifty-styles>
  <!-- +++++++++++++++++++++++++++++++++++++ -->
  <!-- style for the button background panel -->
  <!-- +++++++++++++++++++++++++++++++++++++ -->
  <style id="nifty-button#panel">
    <attributes backgroundImage="button/button.png" imageMode="sprite-resize:100,23,0,2,96,2,2,2,96,2,19,2,96,2,2" paddingLeft="7px" paddingRight="7px" width="100px" height="23px" childLayout="center" visibleToMouse="true" />
    <effect>
      <onHover name="border" color="#822f" post="true" />
      <onFocus name="imageOverlay" filename="button/button.png" imageMode="sprite-resize:100,23,1,2,96,2,2,2,96,2,19,2,96,2,2" post="true" />
      <onEnabled name="renderQuad" startColor="#2228" endColor="#2220" post="true" length="150" />
      <onDisabled name="renderQuad" startColor="#2220" endColor="#2228" post="true" length="150" />
    </effect>
  </style>

  <!-- +++++++++++++++++++++++++++++++++++++ -->
  <!-- style for the button text -->
  <!-- +++++++++++++++++++++++++++++++++++++ -->
  <style id="nifty-button#text" base="button-font">
    <attributes align="center" valign="center" textHAlign="center" textVAlign="center" visibleToMouse="false"/>
    <effect>
      <onEnabled name="textColorAnimated" startColor="#8886" endColor="#eeef" post="false" length="150" />
      <onDisabled name="textColorAnimated" startColor="#eeef" endColor="#8886" post="false" length="150" />
    </effect>
  </style>
</nifty-styles>
```
