### ISSUE TITLE
java.lang.IllegalArgumentException: argument type mismatch after clicking into an TextField

### ISSUE THREAD

**Issue by oberien** [nifty-gui/nifty-gui#270]
Hi,

I'm trying to create an interactive UI and had to implement Mouse- and Key-Events like described in the 13th answer in this thread: http://slick.ninjacave.com/forum/viewtopic.php?t=3436 (Posted: Fri Jul 01, 2011 3:13 pm by arielsan), which works properly as I couldn't get any other InputControllers working. But thats not the issue. I can create elements and use events by interacting and eventSubscribing.

But every time I click into an TextField, a long exception is thrown:

``` java
Aug 19, 2014 10:23:10 PM de.lessvoid.nifty.NiftyMethodInvoker callMethod
WARNING: RuntimeException in callMethod(public void view.gui.controllers.GameSetupScreenController.onClick(java.lang.String,de.lessvoid.nifty.elements.events.NiftyMousePrimaryClickedEvent)) for [view.gui.controllers.GameSetupScreenController@29c19925]
java.lang.IllegalArgumentException: argument type mismatch
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at de.lessvoid.nifty.NiftyMethodInvoker.callMethod(NiftyMethodInvoker.java:157)
    at de.lessvoid.nifty.NiftyMethodInvoker.performInvoke(NiftyMethodInvoker.java:112)
    at de.lessvoid.nifty.Nifty$DelayedMethodInvoke.perform(Nifty.java:1388)
    at de.lessvoid.nifty.Nifty.invokeMethods(Nifty.java:1364)
    at de.lessvoid.nifty.Nifty.handleDynamicElements(Nifty.java:389)
    at de.lessvoid.nifty.Nifty.access$1600(Nifty.java:52)
    at de.lessvoid.nifty.Nifty$NiftyInputConsumerImpl.processEvent(Nifty.java:1621)
    at de.lessvoid.nifty.Nifty$NiftyInputConsumerImpl.processMouseEvent(Nifty.java:1559)
    at view.gui.event.MouseEvent.processMouseEvents(MouseEvent.java:21)
    at view.gamesstates.GameStarting$1.forwardEvents(GameStarting.java:109)
    at de.lessvoid.nifty.Nifty.update(Nifty.java:318)
    at view.gamesstates.NiftyMenu.update(NiftyMenu.java:26)
    at org.newdawn.slick.state.StateBasedGame.update(StateBasedGame.java:266)
    at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:663)
    at org.newdawn.slick.AppGameContainer.gameLoop(AppGameContainer.java:411)
    at org.newdawn.slick.AppGameContainer.start(AppGameContainer.java:321)
    at view.ViewStarter.main(ViewStarter.java:34)
```

I found a similar issue in the sourceforge-appearance here: http://sourceforge.net/p/nifty-gui/discussion/807893/thread/58ed1ea7/
As this thread has never been finished I'd like to ask, how this bug can be fixed or whether there is a workaround around this annoying Exception.

Thank you!
BH16

**Comment by oberien** [comment]
OK, actually i found a workaround to prevent the Exception from being thrown, but creating another bug. If I catch the onClick-event by 

``` xml
<interact onClick="tfpressed()"/>
```

and implementing tfpressed like so in the ScreenController:

``` java
public boolean tfpressed() {
    System.out.println("tfpressed");
    return true;
}
```

no Exception is thrown and the sysout is performed correctly. But trying to select a new cursor position nothing happens, because the event has been consumed...

So is there another way to actually fix the Exception's throw or do I have to use this not really working workaround for every TextField?

Regards,
BH16

**Comment by void256** [comment]
Please show a bit more code!

Besides that I think what this Exception means:

> callMethod(public void view.gui.controllers.GameSetupScreenController.onClick(java.lang.String,de.lessvoid.nifty.elements.events.NiftyMousePrimaryClickedEvent)) for [view.gui.controllers.GameSetupScreenController@29c19925]

is that Nifty will try to lookup a method with the name "onClick" but the parameters of the method in your GameSetupScreenController and what Nifty found in your XML/Builder does not match. If I remember correctly you can only have String parameters but not a NiftyMousePrimaryClickedEvent.

I think you're messing up the Eventhandler-based methods with the interact-based methods eventually.

But I think it will be more clear if you would share a bit of your code.

**Comment by oberien** [comment]
Thank you for the reply!

Trying to create an sscce I found out, that this issue only happens when using EventSubscribing. If I don't have an even-subscribing method in my Controller, I won't get the Exception. I can handle all events with interacts and the error doesn't occur, I don't even have to use my workaround. 
But if I use the example from the manual:

``` java
@NiftyEventSubscriber(id="textField")
public void onClick(String id, NiftyMousePrimaryClickedEvent event) {
    System.out.println("element with id [" + id + "] clicked at [" + event.getMouseX() +
    ", " + event.getMouseY() + "]");
}
```

I will get the Exception.

Even though I will now handle events with interacts and without a single event subscription and don't need this error to be fixed anymore, i will provide a sscce throwing that Exception onClick into the textfield, so you can replicate the Exception and maybe fix it.

SSCCE (just litte modified code from the ninjacave-forum-link):

``` java
import java.util.ArrayList;
import java.util.List;

import org.newdawn.slick.AppGameContainer;
import org.newdawn.slick.GameContainer;
import org.newdawn.slick.Graphics;
import org.newdawn.slick.SlickException;
import org.newdawn.slick.opengl.SlickCallable;
import org.newdawn.slick.state.BasicGameState;
import org.newdawn.slick.state.StateBasedGame;

import de.lessvoid.nifty.Nifty;
import de.lessvoid.nifty.NiftyEventSubscriber;
import de.lessvoid.nifty.NiftyInputConsumer;
import de.lessvoid.nifty.builder.LayerBuilder;
import de.lessvoid.nifty.builder.PanelBuilder;
import de.lessvoid.nifty.builder.ScreenBuilder;
import de.lessvoid.nifty.controls.button.builder.ButtonBuilder;
import de.lessvoid.nifty.controls.textfield.builder.TextFieldBuilder;
import de.lessvoid.nifty.elements.events.NiftyMousePrimaryClickedEvent;
import de.lessvoid.nifty.input.keyboard.KeyboardInputEvent;
import de.lessvoid.nifty.nulldevice.NullSoundDevice;
import de.lessvoid.nifty.renderer.lwjgl.input.LwjglKeyboardInputEventCreator;
import de.lessvoid.nifty.renderer.lwjgl.render.LwjglRenderDevice;
import de.lessvoid.nifty.screen.Screen;
import de.lessvoid.nifty.screen.ScreenController;
import de.lessvoid.nifty.spi.input.InputSystem;
import de.lessvoid.nifty.tools.TimeProvider;
import de.lessvoid.nifty.tools.resourceloader.NiftyResourceLoader;

public class MyNiftySlickGame extends StateBasedGame {

    class MouseEvent {
        private int mouseX;
        private int mouseY;
        private int mouseWheel;
        private int button;
        private boolean buttonDown;

        public MouseEvent(final int mouseX, final int mouseY,
                final boolean mouseDown, final int mouseButton) {
            this.mouseX = mouseX;
            this.mouseY = mouseY;
            this.buttonDown = mouseDown;
            this.button = mouseButton;
            this.mouseWheel = 0;
        }

        public void processMouseEvents(
                final NiftyInputConsumer inputEventConsumer) {
            inputEventConsumer.processMouseEvent(mouseX, mouseY, mouseWheel,
                    button, buttonDown);
        }
    }

    class ScreenControllerExample implements ScreenController {
        public void bind(Nifty arg0, Screen arg1) {
        }

        public void onEndScreen() {
        }

        public void onStartScreen() {
        }

        @NiftyEventSubscriber(id="textField")
        public void onClick(String id, NiftyMousePrimaryClickedEvent event) {
        System.out.println("element with id [" + id + "] clicked at [" + event.getMouseX() +
        ", " + event.getMouseY() + "]");
        }
    }

    private GameContainer container;
    private List<MouseEvent> mouseEvents = new ArrayList<MouseEvent>();
    private List<KeyboardInputEvent> keyEvents = new ArrayList<KeyboardInputEvent>();
    private LwjglKeyboardInputEventCreator inputEventCreator = new LwjglKeyboardInputEventCreator();

    class MainMenuGameState extends BasicGameState {

        private Nifty nifty;

        public void init(GameContainer container, StateBasedGame game)
                throws SlickException {
            nifty = new Nifty(new LwjglRenderDevice(), new NullSoundDevice(),
                    new InputSystem() {
                        public void forwardEvents(
                                final NiftyInputConsumer inputEventConsumer) {
                            for (MouseEvent event : mouseEvents) {
                                event.processMouseEvents(inputEventConsumer);
                            }
                            mouseEvents.clear();

                            for (KeyboardInputEvent event : keyEvents) {
                                inputEventConsumer.processKeyboardEvent(event);
                            }
                            keyEvents.clear();
                        }

                        public void setMousePosition(int x, int y) {

                        }

                        @Override
                        public void setResourceLoader(
                                NiftyResourceLoader niftyResourceLoader) {

                        }

                    }, new TimeProvider());

            nifty.loadStyleFile("nifty-default-styles.xml");
            nifty.loadControlFile("nifty-default-controls.xml");

            Screen mainScreen = new ScreenBuilder("main") {{
                controller(new ScreenControllerExample());
                layer(new LayerBuilder("layer") {{
                    childLayoutCenter();
                    panel(new PanelBuilder("dialog-parent") {{
                            height("200px");
                            width("200px");
                            style("nifty-panel");
                            align(Align.Center);
                            valign(VAlign.Center);
                            childLayoutVertical();
                            control(new ButtonBuilder("SelGrpBt") {{
                                label("Select Group");
                                width("120px");
                                height("40px");
                                align(Align.Center);
                            }});
                            control(new ButtonBuilder("SelDngBt") {{
                                label("Select Dungeon");
                                width("120px");
                                height("40px");
                                align(Align.Center);
                            }});
                            control(new ButtonBuilder("Options") {{
                                    label("Options");
                                    width("120px");
                                    height("40px");
                                    align(Align.Center);
                                }
                            });
                            control(new ButtonBuilder("ExitGame") {{
                                label("Exit Game");
                                width("120px");
                                height("40px");
                                align(Align.Center);
                            }});
                            control(new TextFieldBuilder("textField", "Textfield") {{
                                width("120px");
                                align(Align.Center);
                                visibleToMouse(true);
                            }});
                        }});
                    }});
                }
            }.build(nifty);

            nifty.addScreen("mainScreen", mainScreen);
            nifty.gotoScreen("mainScreen");
        }

        public void update(GameContainer container, StateBasedGame game,
                int delta) throws SlickException {
            nifty.update();
        }

        public void render(GameContainer container, StateBasedGame game,
                Graphics g) throws SlickException {
            SlickCallable.enterSafeBlock();
            nifty.render(false);
            SlickCallable.leaveSafeBlock();
        }

        @Override
        public int getID() {
            return 0;
        }
    }

    public MyNiftySlickGame(String name) {
        super(name);
        addState(new MainMenuGameState());
    }

    public static void main(String[] args) throws SlickException {
        MyNiftySlickGame game = new MyNiftySlickGame("Nifty Slick Example");

        AppGameContainer app = new AppGameContainer(game);
        app.setDisplayMode(800, 600, false);
        app.setAlwaysRender(true);
        app.setFullscreen(false);
        app.setForceExit(true);
        app.start();
    }

    @Override
    public void initStatesList(GameContainer container) throws SlickException {
        this.container = container;
    }

    /**
     * mouse x.
     */
    protected int mouseX;

    /**
     * mouse y.
     */
    protected int mouseY;

    /**
     * mouse down.
     */
    protected boolean mouseDown;

    /**
     * 
     * @param mouseX
     * @param mouseY
     * @param mouseDown
     */
    private void forwardMouseEventToNifty(final int mouseX, final int mouseY,
            final boolean mouseDown) {
        // FIXME: add support for more mouse buttons (this assumes left mouse
        // button click currently)
        mouseEvents.add(new MouseEvent(mouseX, mouseY, mouseDown, 0));
    }

    /**
     * @see org.newdawn.slick.InputListener#mouseMoved(int, int, int, int)
     */
    public void mouseMoved(final int oldx, final int oldy, final int newx,
            final int newy) {
        mouseX = newx;
        mouseY = newy;
        forwardMouseEventToNifty(mouseX, mouseY, mouseDown);
    }

    /**
     * @see org.newdawn.slick.InputListener#mousePressed(int, int, int)
     */
    public void mousePressed(final int button, final int x, final int y) {
        mouseX = x;
        mouseY = y;
        mouseDown = true;
        forwardMouseEventToNifty(mouseX, mouseY, mouseDown);
    }

    /**
     * @see org.newdawn.slick.InputListener#mouseReleased(int, int, int)
     */
    public void mouseReleased(final int button, final int x, final int y) {
        mouseX = x;
        mouseY = y;
        mouseDown = false;
        forwardMouseEventToNifty(mouseX, mouseY, mouseDown);
    }

    /**
     * @see org.newdawn.slick.InputListener#keyPressed(int, char)
     */
    public void keyPressed(final int key, final char c) {
        keyEvents.add(inputEventCreator.createEvent(key, c, true));
    }

    /**
     * @see org.newdawn.slick.InputListener#keyReleased(int, char)
     */
    public void keyReleased(final int key, final char c) {
        keyEvents.add(inputEventCreator.createEvent(key, c, false));
    }
}
```

Regards,
BH16

**Comment by void256** [comment]
Thanks for the SSCCE! :smile: It's all clear now! :wink:

Here is what is happening:

The problem is caused simply by the name `onClick` that you gave your `@NiftyEventSubscriber` method :wink:

The TextFieldControl internally uses this code:

```
    <controlDefinition style="nifty-textfield" name="textfield" ... more-stuff-removed>
        <panel style="#panel" focusable="true">
            <interact onClick="onClick()" onClickMouseMove="onClickMouseMove()"/>
             ...
```

There is an onClick() method inside the TextFieldControl that is used internally to handle the positioning of the cursor in the textfield.

If you name your @NiftyEventSubscriber method exactly the same: `onClick` then Nifty will still detect the method and will try to match the parameters which won't workout and therefore you'll get the IllegalArgumentException.

There are two solutions:
1. You simply rename your `@NiftyEventSubscriber` method to something other than `onClick`  and it will work!
2. Nifty will consume the onClick() event in the TextFieldControl. This is possible and I've just tried that and it works, e.g. your onClick() method on the ScreenController is not called anymore. However I hesitate a bit because there might be code existing that depends on that. If you have a regular and correct onClick() method on the ScreenController then Nifty will correctly call that even though it has been handled inside the TextFieldControl already. 

Opinions about 2.? @3xp0n3nt @mkaring :wink:

PS: When someone runs the SSCCE as is, it will cause a different Exception because the ScreenController class in the example is not public:

```
20.08.2014 01:04:16 de.lessvoid.nifty.NiftyEventAnnotationProcessor$Subscriber onEvent
WARNUNG: failed to invoke method [public void MyNiftySlickGame$ScreenControllerExample.onClick(java.lang.String,de.lessvoid.nifty.elements.events.NiftyMousePrimaryClickedEvent)] with Exception [Class de.lessvoid.nifty.NiftyEventAnnotationProcessor$Subscriber can not access a member of class MyNiftySlickGame$ScreenControllerExample with modifiers "public"][null]
java.lang.IllegalAccessException: Class de.lessvoid.nifty.NiftyEventAnnotationProcessor$Subscriber can not access a member of class MyNiftySlickGame$ScreenControllerExample with modifiers "public"
```

Changing the ScreenController to a public inner class will generate the original Exception:

```
20.08.2014 01:04:42 de.lessvoid.nifty.NiftyMethodInvoker callMethod
WARNUNG: RuntimeException in callMethod(public void MyNiftySlickGame$ScreenControllerExample.onClick(java.lang.String,de.lessvoid.nifty.elements.events.NiftyMousePrimaryClickedEvent)) for [MyNiftySlickGame$ScreenControllerExample@2d26c6ea]
java.lang.IllegalArgumentException: argument type mismatch
```

**Comment by oberien** [comment]
Ah, ok, thank you. So by using the code snippets from the manual, I create an error LOL :D I think someone may have to change the manual, so that no other people will get this error. Or is the number of ppl creating this error is so low, that it doesn't even matter? :)

Thank you for the detailed explanation, but I think I will use interact anyways.

Kind Regards,
BH16

PS: Using Nifty 1.4 official release, I don't get the Exceptions you posted in your PS...

**Comment by ghost** [comment]
> void256 commented 10 hours ago
> 
> If you have a regular and correct onClick() method on the ScreenController then Nifty will correctly call that even though it has been handled inside the TextFieldControl already.

That statement scares me ;-).

First off, I think it's fine to have reserved method names for internal use, but there needs to be 1) a clear error message & 2) clear documentation.

It may not be feasible, but I think the ideal solution would be to have Nifty's AnnotationProcessor explicitly check user's methods against a list of reserved method names. I think it can only be enforced at runtime due to the nature of `EventBus`.

But giving the user `java.lang.IllegalArgumentException: argument type mismatch` is just evil. And really it was just a coincidence that it threw an error at all because like you said if the method signature matched it would actually work - which is even worse in my opinion.

On the other hand, We could change the internal method names to be something that would be much less likely to ever be used, perhaps `interact onClick="onClickInternal()""` or, to be really anal about it:
`interact onClick="onNiftyTextFieldClickInternal()"`.

`onClick()` is way too generic of a name to be reserved if you aren't reserving it either at compile time or  at least runtime.

Another question that comes to mind, however: Is there a way to get rid of the entire `interact onClick` scenario internally? Can't we get around that by using annotations? I thought that was the outdated way of doing things anyway.
