### ISSUE TITLE
[help needed] Create drag-and-drop inventory screen(s)

### ISSUE THREAD

**Issue by spaceemotion** [nifty-gui/nifty-gui#285]
I saw that nifty-controls comes with drag-and-drop controls and tried to make an inventory screen with that. Given that my inventories have slots and items that can be "dragged" and "dropped" from slot to slot (not just _\_click*\* and they pop up somewhere else :D) I thought about mixing these two.

Here's my idea: I have a container/control that is called "inventorySlot". It contains a "droppable" control to allow other items dropping in. The droppable control contains a "draggable" control which then contains my "itemstack" control (its a panel with the item, the stack size as a text, a durability bar and things like that).

So all-in-all here's what i currently looks like in XML form:

``` xml
<!-- Control definitions -->
    <controlDefinition style="my-itemStack" name="itemStack">
        <panel childLayout="vertical" width="32px" height="36px">
            <text id="#label" style="#label" textVAlign="bottom" valign="bottom" textHAlign="right"
                  width="100%" height="32px" marginBottom="2px" />
            <panel id="#durability" childLayout="horizontal" width="100%" height="2px" valign="bottom" />
        </panel>
    </controlDefinition>

    <controlDefinition style="my-inventorySlot" name="inventorySlot">
        <control id="#droppable" name="droppable">
            <control name="draggable">
                <control name="itemStack" />
            </control>
        </control>
    </controlDefinition>

<!-- Style definitions -->

    <!-- Item Stacks -->
    <style id="my-itemStack">
        <effect>
            <onCustom name="itemStack" length="infinite" />
        </effect>
    </style>
    <style id="my-itemStack#label" base="base-font-xs">
        <attributes color="#fff" />
    </style>
    <style id="my-itemStack#durability">
        <attributes backgroundColor="#2e1f" visibleToMouse="false" />
    </style>

    <!-- Inventory slot -->
    <style id="my-inventorySlot">
        <attributes margin="1px" />
    </style>
    <style id="my-inventorySlot#droppable">
        <attributes childLayout="center" width="40px" height="40px" padding="1px" />

        <effect overlay="true">
            <onHover name="colorBar" color="#fff1" post="true" inset="1px" />
            <onHover name="border" color="#fff5" post="true" />
        </effect>
    </style>
```

In theory I was sure that it could work. As I tried the code though - i got errors:

``` log
[18:07:44] [Client thread/FATAL]: Unreported exception thrown!
java.lang.RuntimeException: missing childLayout attribute for an element with [1] child elements. Attributes of error element [id => hopperSlot0#droppable#droppableContent#draggableContent, childRootId => #draggableContent, $$$originalValue->controller => de.lessvoid.nifty.controls.dragndrop.DraggableControl, name => draggable, $$$originalValue->id => #draggableContent, $$$originalValue->name => draggable, controller => de.lessvoid.nifty.controls.dragndrop.DraggableControl, $$$originalValue->childRootId => #draggableContent]
    at de.lessvoid.nifty.loaderv2.types.ElementType.enforceChildLayout(ElementType.java:213) ~[ElementType.class:?]
    at de.lessvoid.nifty.loaderv2.types.ElementType.applyStandard(ElementType.java:202) ~[ElementType.class:?]
    at de.lessvoid.nifty.loaderv2.types.ElementType.create(ElementType.java:161) ~[ElementType.class:?]
    at de.lessvoid.nifty.loaderv2.types.ElementType.create(ElementType.java:150) ~[ElementType.class:?]
    at de.lessvoid.nifty.loaderv2.types.ElementType.applyChildren(ElementType.java:289) ~[ElementType.class:?]
    at de.lessvoid.nifty.loaderv2.types.ElementType.applyStandard(ElementType.java:201) ~[ElementType.class:?]
    at de.lessvoid.nifty.loaderv2.types.ElementType.create(ElementType.java:161) ~[ElementType.class:?]
    at de.lessvoid.nifty.loaderv2.types.ElementType.create(ElementType.java:150) ~[ElementType.class:?]
    at de.lessvoid.nifty.loaderv2.types.ElementType.applyChildren(ElementType.java:289) ~[ElementType.class:?]
    at de.lessvoid.nifty.loaderv2.types.ElementType.applyStandard(ElementType.java:201) ~[ElementType.class:?]
    at de.lessvoid.nifty.loaderv2.types.ElementType.create(ElementType.java:161) ~[ElementType.class:?]
    at de.lessvoid.nifty.loaderv2.types.ElementType.create(ElementType.java:150) ~[ElementType.class:?]
    at de.lessvoid.nifty.loaderv2.types.ElementType.applyChildren(ElementType.java:289) ~[ElementType.class:?]
    at de.lessvoid.nifty.loaderv2.types.ElementType.applyStandard(ElementType.java:201) ~[ElementType.class:?]
    at de.lessvoid.nifty.loaderv2.types.ElementType.create(ElementType.java:161) ~[ElementType.class:?]
    at de.lessvoid.nifty.loaderv2.types.ElementType.create(ElementType.java:150) ~[ElementType.class:?]
    at de.lessvoid.nifty.loaderv2.types.ElementType.applyChildren(ElementType.java:289) ~[ElementType.class:?]
    at de.lessvoid.nifty.loaderv2.types.ElementType.applyStandard(ElementType.java:201) ~[ElementType.class:?]
    at de.lessvoid.nifty.loaderv2.types.ElementType.create(ElementType.java:161) ~[ElementType.class:?]
    at de.lessvoid.nifty.loaderv2.types.ElementType.create(ElementType.java:150) ~[ElementType.class:?]
    at de.lessvoid.nifty.loaderv2.types.ElementType.applyChildren(ElementType.java:289) ~[ElementType.class:?]
    at de.lessvoid.nifty.loaderv2.types.ElementType.applyStandard(ElementType.java:201) ~[ElementType.class:?]
    at de.lessvoid.nifty.loaderv2.types.ElementType.create(ElementType.java:161) ~[ElementType.class:?]
    at de.lessvoid.nifty.loaderv2.types.ElementType.create(ElementType.java:150) ~[ElementType.class:?]
    ...
```

I tried adding `childLayout="center"` to various elements like `#draggable` and `#droppable` but I got the same error every time.

Is there an easier way to create an inventory system? Am I doing something wrong (again)?

Thanks in advance!

**Comment by relu91** [comment]
I think that the problem is that you are not setting the childLayout in droppableContent, see [this line](https://github.com/void256/nifty-gui/blob/1.4/nifty-controls/src/main/resources/nifty-controls/nifty-dragndrop.xml#L6). You must define a new stile that will set the child layout in that panel :+1:

**Comment by spaceemotion** [comment]
@relu91 Thanks! True that I didnt try that one yet, but after adding this:

``` xml
<style id="my-inventorySlot#droppableContent">
    <attributes childLayout="center" />
</style>
```

It crashed again:

``` log
java.lang.RuntimeException: missing childLayout attribute for an element with [1] child elements. Attributes of error element [id => furnaceSlot0#droppable#droppableContent#draggableContent, childRootId => #draggableContent, $$$originalValue->controller => de.lessvoid.nifty.controls.dragndrop.DraggableControl, name => draggable, $$$originalValue->id => #draggableContent, $$$originalValue->name => draggable, controller => de.lessvoid.nifty.controls.dragndrop.DraggableControl, $$$originalValue->childRootId => #draggableContent]
    at de.lessvoid.nifty.loaderv2.types.ElementType.enforceChildLayout(ElementType.java:213)
    at de.lessvoid.nifty.loaderv2.types.ElementType.applyStandard(ElementType.java:202)
    at de.lessvoid.nifty.loaderv2.types.ElementType.create(ElementType.java:161)
    at de.lessvoid.nifty.loaderv2.types.ElementType.create(ElementType.java:150)
    at de.lessvoid.nifty.loaderv2.types.ElementType.applyChildren(ElementType.java:289)
    at de.lessvoid.nifty.loaderv2.types.ElementType.applyStandard(ElementType.java:201)
    at de.lessvoid.nifty.loaderv2.types.ElementType.create(ElementType.java:161)
    at de.lessvoid.nifty.loaderv2.types.ElementType.create(ElementType.java:150)
    at de.lessvoid.nifty.loaderv2.types.ElementType.applyChildren(ElementType.java:289)
    at de.lessvoid.nifty.loaderv2.types.ElementType.applyStandard(ElementType.java:201)
    at de.lessvoid.nifty.loaderv2.types.ElementType.create(ElementType.java:161)
    at de.lessvoid.nifty.loaderv2.types.ElementType.create(ElementType.java:150)
    at de.lessvoid.nifty.loaderv2.types.ElementType.applyChildren(ElementType.java:289)
    at de.lessvoid.nifty.loaderv2.types.ElementType.applyStandard(ElementType.java:201)
    at de.lessvoid.nifty.loaderv2.types.ElementType.create(ElementType.java:161)
    at de.lessvoid.nifty.loaderv2.types.ElementType.create(ElementType.java:150)
    at de.lessvoid.nifty.loaderv2.types.ElementType.applyChildren(ElementType.java:289)
    at de.lessvoid.nifty.loaderv2.types.ElementType.applyStandard(ElementType.java:201)
    at de.lessvoid.nifty.loaderv2.types.ElementType.create(ElementType.java:161)
    at de.lessvoid.nifty.loaderv2.types.ElementType.create(ElementType.java:150)
    at de.lessvoid.nifty.loaderv2.types.ElementType.applyChildren(ElementType.java:289)
    at de.lessvoid.nifty.loaderv2.types.ElementType.applyStandard(ElementType.java:201)
    at de.lessvoid.nifty.loaderv2.types.ElementType.create(ElementType.java:161)
    at de.lessvoid.nifty.loaderv2.types.ElementType.create(ElementType.java:150)
    ...
```

**Comment by relu91** [comment]
You are probably hitting the #105 , see there for workarounds .

**Comment by spaceemotion** [comment]
Yup, that did the trick - thanks!
