### ISSUE TITLE
Nifty-GUI 1.4 slick2d examples not working

### ISSUE THREAD

**Issue by vincaslt** [nifty-gui/nifty-gui#300]
The steps that I used to build project were:

```
cd /tmp
git clone git://github.com/void256/nifty-gui.git
cd nifty-gui/
git checkout 1.4
mvn clean install
cd nifty-examples-slick2d/
export MAVEN_OPTS=-Djava.library.path=target/natives/
mvn exec:java -Dexec.mainClass="de.lessvoid.nifty.examples.slick2d.all.AllDemoMain"
```

The 1.3 examples work splendidly, but using the same steps, I can't get 1.4 slick examples to work. I have tried lwjgl, libgdx examples, and they worked fine. Here are the warnings and errors:

```
[WARNING] Warning: killAfter is now deprecated. Do you need it ? Please comment on MEXEC-6.
[WARNING] 
java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:293)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: de/lessvoid/nifty/examples/all/AllExamples
    at de.lessvoid.nifty.examples.slick2d.all.AllDemoMain.main(AllDemoMain.java:18)
    ... 6 more
Caused by: java.lang.ClassNotFoundException: de.lessvoid.nifty.examples.all.AllExamples
    at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 7 more
```

```
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.3.2:java (default-cli) on project nifty-examples-slick2d: An exception occured while executing the Java class. null: InvocationTargetException: de/lessvoid/nifty/examples/all/AllExamples: de.lessvoid.nifty.examples.all.AllExamples -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**Comment by void256** [comment]
git pull and then build locally the slick examples project `mvn clean install`and then run it again and it should work :)

There was a missing jorbis dependeny which I've just added in this commit: b0976913e5c5a131f3144b89d143701f888ca5f8 and somehow the latest snapshot was not deployed correclty so that you have to build/install it locally (not sure why this is necessary tho).

I've tried it now with the commands you posted and it works for me now.

**Comment by vincaslt** [comment]
Great job, works perfectly now.

Guess I should've figured it out myself, but I'm totally new to maven :D
