### ISSUE TITLE
Can't build a TextField

### ISSUE THREAD

**Issue by vincaslt** [nifty-gui/nifty-gui#307]
I am trying to build a textfield for slick2d just like it is said in manual. In prepareNifty() I write:

``` Java
Screen screen = new ScreenBuilder("start") {{
    controller(new DefaultScreenController());
    layer(new LayerBuilder("layer") {{
        childLayoutCenter();
        backgroundColor("#005f");
        control(new TextFieldBuilder("input", "hello textfield") {{
            width("200px");
        }});
    }});
}}.build(nifty);
```

And there is only a blue screen. These are the warnings:

```
Sau 11, 2015 12:55:07 AM de.lessvoid.nifty.Nifty gotoScreenInternal
WARNING: screen [start] not found
Sau 11, 2015 12:55:07 AM de.lessvoid.nifty.loaderv2.types.ControlType internalApplyControl
WARNING: controlDefinition [textfield] missing.
Sau 11, 2015 12:55:07 AM de.lessvoid.nifty.Nifty gotoScreenInternal
WARNING: screen [start] not found
```

**Comment by void256** [comment]
You need to include the default controls and the default styles jar and add them to your nifty instance like so:

```
    nifty.loadStyleFile("nifty-default-styles.xml");
    nifty.loadControlFile("nifty-default-controls.xml");
```

The  `WARNING: controlDefinition [textfield] missing.` is the key here. Sorry about the manual not telling you. I think it's telling you somewhere but not in that specific example.

**Comment by vincaslt** [comment]
Ok, that helped a little, also it seemed, that my styles .jar didn't get imported for some reason, after checking dependencies, and writing those two lines I'm now getting this exception:

```
Exception in thread "main" java.lang.NoSuchMethodError: org.newdawn.slick.Font.getWidth(Ljava/lang/CharSequence;)I
    at de.lessvoid.nifty.slick2d.render.font.AbstractSlickRenderFont.getWidth(AbstractSlickRenderFont.java:81)
    at de.lessvoid.nifty.elements.render.TextRenderer.initText(TextRenderer.java:199)
    at de.lessvoid.nifty.elements.render.TextRenderer.setText(TextRenderer.java:164)
    at de.lessvoid.nifty.loaderv2.types.apply.ApplyRenderText.apply(ApplyRenderText.java:35)
    at de.lessvoid.nifty.elements.Element.initializeFromAttributes(Element.java:373)
    at de.lessvoid.nifty.loaderv2.types.ElementType.applyAttributes(ElementType.java:257)
    at de.lessvoid.nifty.loaderv2.types.ElementType.applyStandard(ElementType.java:198)
    at de.lessvoid.nifty.loaderv2.types.ElementType.create(ElementType.java:161)
    at de.lessvoid.nifty.loaderv2.types.ElementType.create(ElementType.java:150)
    at de.lessvoid.nifty.loaderv2.types.ElementType.applyChildren(ElementType.java:289)
    at de.lessvoid.nifty.loaderv2.types.ElementType.applyStandard(ElementType.java:201)
    at de.lessvoid.nifty.loaderv2.types.ElementType.create(ElementType.java:161)
    at de.lessvoid.nifty.loaderv2.types.ElementType.create(ElementType.java:150)
    at de.lessvoid.nifty.loaderv2.types.ElementType.applyChildren(ElementType.java:289)
    at de.lessvoid.nifty.loaderv2.types.ElementType.applyStandard(ElementType.java:201)
    at de.lessvoid.nifty.loaderv2.types.ElementType.create(ElementType.java:161)
    at de.lessvoid.nifty.loaderv2.types.ElementType.create(ElementType.java:150)
    at de.lessvoid.nifty.loaderv2.types.ElementType.applyChildren(ElementType.java:289)
    at de.lessvoid.nifty.loaderv2.types.ElementType.applyStandard(ElementType.java:201)
    at de.lessvoid.nifty.loaderv2.types.ElementType.create(ElementType.java:161)
    at de.lessvoid.nifty.Nifty.createElementFromTypeInternal(Nifty.java:1726)
    at de.lessvoid.nifty.Nifty.createElementFromType(Nifty.java:1711)
    at de.lessvoid.nifty.builder.ElementBuilder.build(ElementBuilder.java:491)
    at de.lessvoid.nifty.builder.LayerBuilder.build(LayerBuilder.java:23)
    at de.lessvoid.nifty.builder.ScreenBuilder.build(ScreenBuilder.java:55)
    at com.darktimes.client.states.LoginState.prepareNifty(LoginState.java:91)
    at de.lessvoid.nifty.slick2d.NiftyOverlayBasicGameState.initNifty(NiftyOverlayBasicGameState.java:378)
    at de.lessvoid.nifty.slick2d.NiftyOverlayBasicGameState.initNifty(NiftyOverlayBasicGameState.java:328)
    at de.lessvoid.nifty.slick2d.NiftyOverlayBasicGameState.initNifty(NiftyOverlayBasicGameState.java:309)
    at de.lessvoid.nifty.slick2d.NiftyBasicGameState.initGameAndGUI(NiftyBasicGameState.java:60)
    at de.lessvoid.nifty.slick2d.NiftyOverlayBasicGameState.init(NiftyOverlayBasicGameState.java:146)
    at org.newdawn.slick.state.StateBasedGame.init(StateBasedGame.java:171)
    at org.newdawn.slick.ScalableGame.init(ScalableGame.java:69)
    at org.newdawn.slick.AppGameContainer.setup(AppGameContainer.java:393)
    at org.newdawn.slick.AppGameContainer.start(AppGameContainer.java:317)
    at com.darktimes.client.DarkTimes.launch(DarkTimes.java:44)
    at com.darktimes.client.DarkTimes.main(DarkTimes.java:52)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
```

**Comment by bgroenks96** [comment]
Do you have Slick2D added as a dependency? If so, are you using the most recent version?

A NoSuchMethod exception would indicate one or both of those preconditions is probably false.

**Comment by vincaslt** [comment]
Getting the latest slick version, yesterday's, from their site, and re-downloading nifty seemed to fix the problem. One concern though, the new version of nifty seems to be spamming console quite a lot, is it supposed to be so?

**Comment by bgroenks96** [comment]
Check if you have 'fine' enabled in log.properties. Otherwise, you can always turn of INFO logging, at least while you don't need it.
