### ISSUE TITLE
LibGDX java.lang.NoSuchFieldError gl10

### ISSUE THREAD

**Issue by Stepets** [nifty-gui/nifty-gui#315]
Hello!
I loaded the latest gdx-setup.jar from badlogicgames, created a project, added those lines to the build.gradle:

``` groovy
        niftyVersion = '1.4.1'
...
        maven { url "http://nifty-gui.sourceforge.net/nifty-maven-repo/" }
...
        compile "lessvoid:nifty:$niftyVersion"
        compile "lessvoid:nifty-default-controls:$niftyVersion"
        compile "lessvoid:nifty-style-black:$niftyVersion"
        compile "lessvoid:nifty-libgdx-renderer:$niftyVersion"
```

folowing code:

``` java
        nifty = new Nifty(new BatchRenderDevice(GdxBatchRenderBackendFactory.create()),
                          new GdxSoundDevice(assetManager),
                          new GdxInputSystem(Gdx.input),
                          new AccurateTimeProvider());
```

causes the exception to be thrown:
Exception in thread "LWJGL Application" com.badlogic.gdx.utils.GdxRuntimeException: java.lang.NoSuchFieldError: gl10
    at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:121)
Caused by: java.lang.NoSuchFieldError: gl10
    at de.lessvoid.nifty.gdx.render.GdxGL.glGetIntegerv(GdxGL.java:378)
    at de.lessvoid.nifty.render.batch.BatchRenderBackendInternal.updateViewport(BatchRenderBackendInternal.java:355)
    at de.lessvoid.nifty.render.batch.BatchRenderBackendInternal.getWidth(BatchRenderBackendInternal.java:113)
    at de.lessvoid.nifty.render.batch.BatchRenderBackendInternal.initializeOpenGL(BatchRenderBackendInternal.java:333)
    at de.lessvoid.nifty.render.batch.BatchRenderBackendInternal.<init>(BatchRenderBackendInternal.java:101)
    at de.lessvoid.nifty.gdx.render.GdxBatchRenderBackendFactory.create(GdxBatchRenderBackendFactory.java:13)
.... nifty = new Nifty(...

How to adapt Nifty to LibGDX?

**Comment by ghost** [comment]
This is a huge project that is in process. Currently, Nifty Gui is only integrated with LibGDX 0.9.9.
