### ISSUE TITLE
Slick2d, Carrier for Nifty is not set yet.

### ISSUE THREAD

**Issue by raLaaa** [nifty-gui/nifty-gui#322]
Hey guys,

I'm developing a slick2d Game with Nifty, I was using Nifty 1.3 a while ago, but decided than to switch up to the current version.
When I was using Nifty 1.3 I was initiliazing the Nifty object via nifty = new Nifty(new LwjglRenderDevice(), new NullSoundDevice(), new LwjglInputSystem(), new TimeProvider());

TimeProvider and LwjglRenderDevice is deprecated now, I googled a bit and found out that the following exception allegedly is caused  by using a new lwjgl version:

Exception in thread "main" java.lang.NoClassDefFoundError: org/lwjgl/util/glu/GLU
    at de.lessvoid.nifty.renderer.lwjgl.render.LwjglRenderImage.createTexture(LwjglRenderImage.java:125)
    at de.lessvoid.nifty.renderer.lwjgl.render.LwjglRenderImage.<init>(LwjglRenderImage.java:47)
    at de.lessvoid.nifty.renderer.lwjgl.render.font.Font.<init>(Font.java:64)
    at de.lessvoid.nifty.renderer.lwjgl.render.LwjglRenderFont.<init>(LwjglRenderFont.java:15)
    at de.lessvoid.nifty.renderer.lwjgl.render.LwjglRenderDevice.createFont(LwjglRenderDevice.java:225)
    at de.lessvoid.nifty.render.ScalingRenderDevice.createFont(ScalingRenderDevice.java:33)
    at de.lessvoid.nifty.render.NiftyRenderEngineImpl.createFont(NiftyRenderEngineImpl.java:196)
    at de.lessvoid.nifty.loaderv2.types.apply.Convert.font(Convert.java:44)
    at de.lessvoid.nifty.loaderv2.types.apply.ApplyRenderText.apply(ApplyRenderText.java:29)
    at de.lessvoid.nifty.elements.Element.initializeFromAttributes(Element.java:376)
    at de.lessvoid.nifty.loaderv2.types.ElementType.applyAttributes(ElementType.java:257)
    at de.lessvoid.nifty.loaderv2.types.ElementType.applyStandard(ElementType.java:198)
    at de.lessvoid.nifty.loaderv2.types.ElementType.create(ElementType.java:161)
    at de.lessvoid.nifty.loaderv2.types.ElementType.create(ElementType.java:150)
    at de.lessvoid.nifty.loaderv2.types.ElementType.applyChildren(ElementType.java:289)
    at de.lessvoid.nifty.loaderv2.types.ElementType.applyStandard(ElementType.java:201)
    at de.lessvoid.nifty.loaderv2.types.ElementType.create(ElementType.java:161)
    at de.lessvoid.nifty.loaderv2.types.ElementType.create(ElementType.java:150)
    at de.lessvoid.nifty.loaderv2.types.ElementType.applyChildren(ElementType.java:289)
    at de.lessvoid.nifty.loaderv2.types.ElementType.applyStandard(ElementType.java:201)
    at de.lessvoid.nifty.loaderv2.types.ElementType.create(ElementType.java:161)
    at de.lessvoid.nifty.loaderv2.types.ElementType.create(ElementType.java:150)
    at de.lessvoid.nifty.loaderv2.types.ElementType.applyChildren(ElementType.java:289)
    at de.lessvoid.nifty.loaderv2.types.ElementType.applyStandard(ElementType.java:201)
    at de.lessvoid.nifty.loaderv2.types.ElementType.create(ElementType.java:161)
    at de.lessvoid.nifty.Nifty.createElementFromTypeInternal(Nifty.java:1816)
    at de.lessvoid.nifty.Nifty.createElementFromType(Nifty.java:1801)
    at de.lessvoid.nifty.builder.ElementBuilder.build(ElementBuilder.java:494)
    at de.lessvoid.nifty.builder.LayerBuilder.build(LayerBuilder.java:23)
    at de.lessvoid.nifty.builder.ScreenBuilder.build(ScreenBuilder.java:55)
    at playerClientGUI.GUIinit.<init>(GUIinit.java:85)
    at playerClientEngine.playerClientGame.init(playerClientGame.java:140)
    at org.newdawn.slick.state.StateBasedGame.init(StateBasedGame.java:171)
    at org.newdawn.slick.AppGameContainer.setup(AppGameContainer.java:393)
    at org.newdawn.slick.AppGameContainer.start(AppGameContainer.java:317)
    at playerClientEngine.playerClientClass.main(playerClientClass.java:152)

So I was reading the nifty apidoc and found out that there is a method called: initNifty(container, game); So I was Trying to use this to initialize nifty but I'm receiving this Exception:

Exception in thread "main" java.lang.IllegalStateException: Carrier for Nifty is not set yet.
    at de.lessvoid.nifty.slick2d.NiftyOverlayGameState.initNifty(NiftyOverlayGameState.java:366)
    at de.lessvoid.nifty.slick2d.NiftyOverlayGameState.initNifty(NiftyOverlayGameState.java:329)
    at de.lessvoid.nifty.slick2d.NiftyOverlayGameState.initNifty(NiftyOverlayGameState.java:310)
    at de.lessvoid.nifty.slick2d.NiftyOverlayGameState.initNifty(NiftyOverlayGameState.java:293)
    at playerClientGUI.GUIinit.<init>(GUIinit.java:53)
    at playerClientEngine.playerClientGame.init(playerClientGame.java:140)
    at org.newdawn.slick.state.StateBasedGame.init(StateBasedGame.java:171)
    at org.newdawn.slick.AppGameContainer.setup(AppGameContainer.java:393)
    at org.newdawn.slick.AppGameContainer.start(AppGameContainer.java:317)
    at playerClientEngine.playerClientClass.main(playerClientClass.java:152)

This is my GUI Class:

public class GUIinit extends NiftyOverlayGameState{

```
/** The nifty. */
public Nifty nifty;

/** The create panel. */
public PanelCreator createPanel;

/** The screen. */
public Screen screen;

/**
 * Instantiates a new GU iinit.
 *
 * @param container the container
 * @param game the game
 */
public GUIinit(GameContainer container, StateBasedGame game){
    initNifty(container, game);
    nifty.loadStyleFile("nifty-default-styles.xml");
    nifty.loadControlFile("nifty-default-controls.xml");    

screen = new ScreenBuilder("main") {{
controller(new ScreenControllerBasic());
    layer(new LayerBuilder("layer") {{
        childLayoutCenter();
        panel(new PanelBuilder("dialog-parent"){{
        height("100px");
            width("100px");
            style("nifty-panel-simple");
            align(Align.Right);
            valign(VAlign.Bottom);
            childLayoutVertical();

            control(new ButtonBuilder("Char Info"){{
            label("C");
                width("12px");
                height("12px");
                align(Align.Left);
                }});
}});


}});
}}.build(nifty);

nifty.addScreen("mainScreen", screen);
nifty.gotoScreen("mainScreen");
}

/**
 * Render gui.
 */
public void renderGUI(){        
SlickCallable.enterSafeBlock();
   nifty.render(false);
    SlickCallable.leaveSafeBlock();     
}

/**
 * Update gui.
 */
public void updateGUI(){
nifty.update();
}

/* (non-Javadoc)
 * @see org.newdawn.slick.state.BasicGameState#getID()
 */
@Override
public int getID() {
    // TODO Auto-generated method stub
    return 0;
}
```

ScreenController:

```
 public  class ScreenControllerBasic implements ScreenController {
          public void bind(Nifty arg0, Screen arg1) {}
          public void onEndScreen() {}
          public void onStartScreen() {}
       }
```

On my Slick2d Game, i'm simply updating and rendering the gui in the updating and rendering methode, it worked for me with Nifty 1.3 and I was able to draw a GUI, I didn't change anything except the nifty version and now I'm receiving the exceptions stated above.

Note: I'm probably doing something wrong and this is not a real bug or something, hopefully someone can help me. Btw. I was reading the slick2d examples from your repo but somehow it didn't really help me to integrate nifty into slick2d because if I'm not wrong you did not work with update, render and init in detail.

best regards

**Comment by bgroenks96** [comment]
Are you using LWJGL 3+? From what I understand, they scrapped the GLU class, so that would be why you are getting a NoClassDefFoundError for it (see #304 ).

For right now, if you're using NIfy with Slick2D, you should make sure you have the latest LWJGL version prior to version 3. I'm fairly certain Slick2D has no dependency on the newer LWJGL version anyway.

Also, you might want to consider using the Slick2D Nifty renderer instead.

**Comment by raLaaa** [comment]
Nope, I'm using lwjgl 2.9.1, I tried to run the slick2d examples as well with that lwjgl version and that worked for me.
What is weird for me is if I use nifty 1.3 I'm not getting any exceptions with the same code.

**Comment by bgroenks96** [comment]
Can you check the actual JAR file (downloaded by Maven if you are using it) and see if the org.lwjgl.util.glu.GLU class actually exists in it?

If you aren't using LWJGL 3, then this is probably just some kind of classpath issue.

**Comment by raLaaa** [comment]
Ahh, nice idea, I should have done that by myself, apparently nifty 1.3 isn't using the GLU class, that why it was working for me, the newest version is tho.
I was able to fix it by adding the class to my classpath.

Your help is very much appreciated, cheers!

**Comment by bgroenks96** [comment]
That's still rather odd.... because it seems the version of LwjglRenderImage on the 1.3 branch does in fact use the class. It may depend on the minor version though, or the RenderDevice implementation.

I'm glad that fixed your problem!
