### ISSUE TITLE
Application crashes when cursor changes

### ISSUE THREAD

**Issue by Genhis** [nifty-gui/nifty-gui#355]
Hello,

I'm trying to use the Console, but I'm getting this error when I move the cursor over the text field.
I'm using Slick2D game library and my class extends NiftyBasicGame.

```
java.lang.UnsupportedOperationException: Use enableCursor(GameContainer container).
    at de.lessvoid.nifty.slick2d.render.cursor.AbstractNativeSlickMouseCursor.enable(AbstractNativeSlickMouseCursor.java:22)
    at de.lessvoid.nifty.render.batch.BatchRenderBackendInternal.enableMouseCursor(BatchRenderBackendInternal.java:154)
    at de.lessvoid.nifty.render.batch.BatchRenderDevice.enableMouseCursor(BatchRenderDevice.java:493)
    at de.lessvoid.nifty.render.NiftyMouseImpl.enableMouseCursor(NiftyMouseImpl.java:87)
    at de.lessvoid.nifty.effects.impl.ChangeMouseCursor.execute(ChangeMouseCursor.java:39)
    at de.lessvoid.nifty.effects.Effect.execute(Effect.java:158)
    at de.lessvoid.nifty.effects.EffectProcessorImpl.renderActive(EffectProcessorImpl.java:308)
    at de.lessvoid.nifty.effects.EffectProcessorImpl.renderPre(EffectProcessorImpl.java:54)
    at de.lessvoid.nifty.effects.EffectManager$RenderPhasePre.render(EffectManager.java:343)
    at de.lessvoid.nifty.effects.EffectManager.renderInternal(EffectManager.java:164)
    at de.lessvoid.nifty.effects.EffectManager.renderPre(EffectManager.java:147)
    at de.lessvoid.nifty.elements.Element.render(Element.java:696)
    at de.lessvoid.nifty.elements.Element.renderInternalChildElements(Element.java:729)
    at de.lessvoid.nifty.elements.Element.renderChildren(Element.java:721)
    at de.lessvoid.nifty.elements.Element.render(Element.java:699)
    at de.lessvoid.nifty.elements.Element.renderInternalChildElements(Element.java:729)
    at de.lessvoid.nifty.elements.Element.renderChildren(Element.java:721)
    at de.lessvoid.nifty.elements.Element.render(Element.java:692)
    at de.lessvoid.nifty.screen.Screen.renderLayers(Screen.java:332)
    at de.lessvoid.nifty.Nifty.render(Nifty.java:402)
    at de.lessvoid.nifty.slick2d.NiftyOverlayBasicGame.render(NiftyOverlayBasicGame.java:135)
```

**Comment by bgroenks96** [comment]
Looks like the Slick2D renderer doesn't support custom cursors at the moment :disappointed: 

Unfortunately, I'm not too familiar with Slick2D (never used it before), but if you have an idea of how to set custom cursors in Slick2D, you're definitely welcome to add support for this! It should be a pretty simple addition to nifty's slick renderer, provided you know how to do it in Slick.

I'm here if you have any questions about what classes to extend and/or what to do with the Nifty side of things.

**Comment by bgroenks96** [comment]
Well I totally lied I guess.... :cold_sweat: 

I went to actually check the code AFTER I wrote my comment.... there is support for a Slick mouse cursor with LWJGL (I assume that's what you're using...?).

It looks like, for whatever reason, your renderer isn't using the Slick mouse cursor.

Can I see your initialization code for the Nifty renderer?

**Comment by Genhis** [comment]
Actually, Nifty initialization code is the default, you can find it in `de.lessvoid.nifty.slick2d.NiftyOverlayBasicGame.initNifty()`.

```
niftyGUI = new Nifty(new BatchRenderDevice(SlickBatchRenderBackendFactory.create()), new SlickSoundDevice(), new SlickSlickInputSystem(this), new LWJGLTimeProvider());
```

**Comment by ghost** [comment]
@Genhis It looks like you're using a ChangeMouseCursor effect, which means you're probably manually registering custom slick mouse cursors with Nifty? Please show us that code.

**Comment by Genhis** [comment]
No, I'm not registering any mouse cursor. This is all my code:

```
nifty.loadStyleFile("nifty-default-styles.xml");
nifty.loadControlFile("nifty-default-controls.xml");

new ScreenBuilder("start") {{
    this.layer(new LayerBuilder("layer") {{
        this.childLayoutAbsolute();
        this.control(new ConsoleBuilder("console") {{
              width("80%");
              lines(25);
              alignCenter();
              valignCenter();
        }});
    }});
}}.build(nifty);
```

**Comment by ghost** [comment]
@Genhis You're not doing anything wrong. I've submitted a bugfix, and I actually caused this bug from an old refactoring that I performed.

After @void256 merges this, all you will have to do now is change the way you're instantiating Nifty to include the GameContainer instance:

new Nifty(new BatchRenderDevice(SlickBatchRenderBackendFactory.create(gameContainer)), new SlickSoundDevice(), new SlickSlickInputSystem(this), new LWJGLTimeProvider());

Or you can use NiftyGameState#initGameAndGUI, and this will be done automatically.

**Comment by 3xp0n3nt** [comment]
@lawallet @void256 Can someone please test the bugfix now that it's merged? Thanks!

**Comment by ghost** [comment]
@Genhis @void256 Can someone please test the bugfix now that it's merged? Thanks!

**Comment by Genhis** [comment]
Tested, it works. Thanks :)

**Comment by bgroenks96** [comment]
Thanks @3xp0n3nt for your help!

**Comment by ghost** [comment]
I do what I can. :sweat_smile:
