### ISSUE TITLE
Nifty examples for jogl, AllDemoMain.java fails to run

### ISSUE THREAD

**Issue by elect86** [nifty-gui/nifty-gui#400]
Hi, I tried to start `AllDemoMain.java` but this is what I get:

```
cd C:\Users\GBarbieri\Documents\NetBeansProjects\nifty-gui\nifty-examples-jogl; "JAVA_HOME=C:\\Program Files\\Java\\jdk1.8.0_60" cmd /c "\"\"C:\\Program Files\\NetBeans 8.1\\java\\maven\\bin\\mvn.bat\" -Dexec.args=\"-classpath %classpath de.lessvoid.nifty.examples.jogl.all.AllDemoMain\" -Dexec.executable=\"C:\\Program Files\\Java\\jdk1.8.0_60\\bin\\java.exe\" -Dexec.classpathScope=runtime -Dmaven.ext.class.path=\"C:\\Program Files\\NetBeans 8.1\\java\\maven-nblib\\netbeans-eventspy.jar;C:\\Program Files\\NetBeans 8.1\\java\\maven-nblib\\netbeans-cos.jar\" -Dfile.encoding=UTF-8 org.codehaus.mojo:exec-maven-plugin:1.2.1:exec\""
Running NetBeans Compile On Save execution. Phase execution is skipped and output directories of dependency projects (with Compile on Save turned on) will be used instead of their jar artifacts.
Scanning for projects...
Inspecting build with total of 1 modules...
Installing Nexus Staging features:
  ... total of 1 executions of maven-deploy-plugin replaced with nexus-staging-maven-plugin

------------------------------------------------------------------------
Building Nifty Examples for JOGL 1.4.2-SNAPSHOT
------------------------------------------------------------------------

--- exec-maven-plugin:1.2.1:exec (default-cli) @ nifty-examples-jogl ---
using mode batch
1453275021456 SEVERE [de.lessvoid.nifty.examples.jogl.NiftyExampleLoaderJOGL] Unable to run Nifty example! Stack trace:
java.lang.RuntimeException: java.lang.NoClassDefFoundError: com/jogamp/opengl/GLContext
    at jogamp.newt.DefaultEDTUtil.invokeImpl(DefaultEDTUtil.java:246)
    at jogamp.newt.DefaultEDTUtil.invoke(DefaultEDTUtil.java:160)
    at jogamp.newt.DisplayImpl.runOnEDTIfAvail(DisplayImpl.java:427)
    at jogamp.newt.WindowImpl.runOnEDTIfAvail(WindowImpl.java:1988)
    at jogamp.newt.WindowImpl.setVisible(WindowImpl.java:978)
    at jogamp.newt.WindowImpl.setVisible(WindowImpl.java:983)
    at com.jogamp.newt.opengl.GLWindow.setVisible(GLWindow.java:441)
    at de.lessvoid.nifty.examples.jogl.JOGLNiftyRunner.run(JOGLNiftyRunner.java:76)
    at de.lessvoid.nifty.examples.jogl.NiftyExampleLoaderJOGL.runWithJOGL(NiftyExampleLoaderJOGL.java:57)
    at de.lessvoid.nifty.examples.jogl.NiftyExampleLoaderJOGL.runWithJOGL(NiftyExampleLoaderJOGL.java:31)
    at de.lessvoid.nifty.examples.jogl.all.AllDemoMain.main(AllDemoMain.java:10)
Caused by: java.lang.NoClassDefFoundError: com/jogamp/opengl/GLContext
    at de.lessvoid.nifty.renderer.jogl.render.JoglGL.glGetIntegerv(JoglGL.java:385)
    at de.lessvoid.nifty.render.batch.BatchRenderBackendInternal.updateViewport(BatchRenderBackendInternal.java:355)
    at de.lessvoid.nifty.render.batch.BatchRenderBackendInternal.getWidth(BatchRenderBackendInternal.java:113)
    at de.lessvoid.nifty.render.batch.BatchRenderBackendInternal.initializeOpenGL(BatchRenderBackendInternal.java:333)
    at de.lessvoid.nifty.render.batch.BatchRenderBackendInternal.<init>(BatchRenderBackendInternal.java:101)
    at de.lessvoid.nifty.renderer.jogl.render.JoglBatchRenderBackendFactory.create(JoglBatchRenderBackendFactory.java:16)
    at de.lessvoid.nifty.examples.jogl.JOGLNiftyRunner.init(JOGLNiftyRunner.java:121)
    at jogamp.opengl.GLDrawableHelper.init(GLDrawableHelper.java:617)
    at jogamp.opengl.GLDrawableHelper.init(GLDrawableHelper.java:639)
    at jogamp.opengl.GLAutoDrawableBase$1.run(GLAutoDrawableBase.java:387)
    at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1117)
    at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:994)
    at com.jogamp.newt.opengl.GLWindow.display(GLWindow.java:621)
    at jogamp.opengl.GLAutoDrawableBase.defaultWindowResizedOp(GLAutoDrawableBase.java:244)
    at com.jogamp.newt.opengl.GLWindow.access$200(GLWindow.java:111)
    at com.jogamp.newt.opengl.GLWindow$2.windowResized(GLWindow.java:133)
    at jogamp.newt.WindowImpl.consumeWindowEvent(WindowImpl.java:3516)
    at jogamp.newt.WindowImpl.sendWindowEvent(WindowImpl.java:3454)
    at jogamp.newt.WindowImpl.setVisibleActionImpl(WindowImpl.java:957)
    at jogamp.newt.WindowImpl$VisibleAction.run(WindowImpl.java:969)
    at com.jogamp.common.util.RunnableTask.run(RunnableTask.java:112)
    at jogamp.newt.DefaultEDTUtil$NEDT.run(DefaultEDTUtil.java:369)
Caused by: java.lang.ClassNotFoundException: com.jogamp.opengl.GLContext
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 22 more
```

Any hint?

**Comment by elect86** [comment]
Ok, I solved, I added in the windows `PATH`  `target/natives`.

Anyway, I run the `UseCase_a05_RotatingChildNode` but I get between 30 and 50 fps on a gtx 770... is it normal?

**Comment by relu91** [comment]
You can also use "-Djava.library.path=target/natives/" as argument of the jvm when running the example!. About fps I don't know, maybe there's a 60 fps active? Surely @void256 could have some more tip!

**Comment by elect86** [comment]
I already tried that, it didn't work out.

Yeah, it's possible, but I don't know where to look for..

**Comment by bgroenks96** [comment]
@elect86 No that's not normal. Does it appear smooth? There might be a bug in the FPS reporting code.

**Comment by elect86** [comment]
Most of the time yes, but every couple of seconds it has some very small freezes

**Comment by bgroenks96** [comment]
Could you make a new issue for that?

And as for the natives issue, `-Djava.library.path` won't work because `exec:java` doesn't spawn a new VM (it's kind of stupid).

The way you fixed it is fine, but if you want a more portable solution, you can set the `MAVEN_OPTS` environment variable. i.e.: `MAVEN_OPTS="-Djava.library.path=target/natives"` and then run the normal command: 

```
mvn exec:java -Dexec.mainClass="de.lessvoid.nifty.examples.usecase.UseCase_a05_RotationChildNodes"
```

Since it seems OP has been solved, I'm going to close this issue. Feel free to re-open if necessary.

**Comment by elect86** [comment]
Sure, no problem
