### ISSUE TITLE
Hints don't support dollar signs

### ISSUE THREAD

**Issue by tonihele** [nifty-gui/nifty-gui#463]
Hints don't support dollar signs. I have UI as XML, and an element as such:
`<control width="8%" name="guiIconNoClick" id="mapPercStat" image="Textures/GUI/Icons/Info/Map_Percent.png" hint="${menu.1528}" />`

Now, if this ${menu.1528} translates to any string with a dollar sign, I get the following error:

> java.lang.RuntimeException: java.lang.IllegalArgumentException: Illegal group reference
> 	at de.lessvoid.nifty.Nifty.loadFromStream(Nifty.java:685)
> 	at de.lessvoid.nifty.Nifty.addXml(Nifty.java:612)
> 	at toniarts.openkeeper.Main$5.onLoad(Main.java:392)
> 	at toniarts.openkeeper.game.state.loading.LoadingState$LoadingThread.lambda$run$0(LoadingState.java:188)
> 	at toniarts.openkeeper.game.state.loading.LoadingState$LoadingThread.run(LoadingState.java:189)
> Caused by: java.lang.IllegalArgumentException: Illegal group reference
> 	at java.util.regex.Matcher.appendReplacement(Matcher.java:857)
> 	at java.util.regex.Matcher.replaceAll(Matcher.java:955)
> 	at java.lang.String.replaceAll(String.java:2223)
> 	at de.lessvoid.xml.xpp3.ControlParameter.applyParameter(ControlParameter.java:31)
> 	at de.lessvoid.xml.xpp3.Attributes.resolveParameters(Attributes.java:424)
> 	at de.lessvoid.nifty.loaderv2.types.ElementType.resolveParameters(ElementType.java:353)
> 	at de.lessvoid.nifty.loaderv2.types.ElementType.resolveParameters(ElementType.java:362)
> 	at de.lessvoid.nifty.loaderv2.types.ElementType.resolveParameters(ElementType.java:362)
> 	at de.lessvoid.nifty.loaderv2.types.ElementType.resolveParameters(ElementType.java:362)
> 	at de.lessvoid.nifty.loaderv2.types.ElementType.resolveParameters(ElementType.java:362)
> 	at de.lessvoid.nifty.loaderv2.types.ElementType.resolveParameters(ElementType.java:362)
> 	at de.lessvoid.nifty.loaderv2.types.ElementType.resolveParameters(ElementType.java:362)
> 	at de.lessvoid.nifty.loaderv2.types.ElementType.prepare(ElementType.java:332)
> 	at de.lessvoid.nifty.loaderv2.types.ScreenType.create(ScreenType.java:96)
> 	at de.lessvoid.nifty.loaderv2.types.NiftyType.create(NiftyType.java:149)
> 	at de.lessvoid.nifty.Nifty.loadFromStream(Nifty.java:678)
> 	... 4 more

If this (ControlParameter):
```
  public String applyParameter(final String originalValue, final String key, final String value) {
    return originalValue.replaceAll("\\$" + key, value).replaceAll("\\$\\(" + key + "\\)", value);
  }
```
Is replaced by:
```
  public String applyParameter(final String originalValue, final String key, final String value) {
    return originalValue.replaceAll("\\$" + key, Matcher.quoteReplacement(value)).replaceAll("\\$\\(" + key + "\\)", value);
  }
```

It works. But I'm not really sure what is happening here, so I have no idea is that a valid fix. Or is there something I could do to avoid this?

**Comment by Genhis** [comment]
Please post sample code to reproduce your issue.

Besides that, `${id.key}` expression is used for GUI localization. Is that what you're trying to do?

Taken from [the manual](https://sourceforge.net/projects/nifty-gui/files/nifty-gui/1.3.2/nifty-gui-the-manual-1.3.2.pdf/download):

> **SPECIAL XML MARKUP**
> Every attribute of every XML element can contain the special markup „${...}“ that gets replaced
> with something else when the XML is loaded. The following values are supported with the „${...}“
> syntax:
>
> **${id.key}**
> Lookup resource bundle with "id" and request "key" from it. This is explained in more detail below
> in the Localization section.
>
> **${ENV.key}**
> Lookup "key" in all of the environment variables (System.getEnv()) and replace „${ENV.key}“ with
> the value of the environment variable „key“.
>
> **${PROP.key}**
> Lookup "key" in the Nifty.setGlobalProperties(Properties) properties or if the properties are not set
> use System.getProperties() to lookup "key".
>
> **${CALL.method()}**
> Call method() at the current ScreenController and replace the value that the method() returns.
> When used in this way then „method()“ should return a String.

**Comment by tonihele** [comment]
I can try to whip something up. But yes, it is localization. The string comes from a resource bundle. This seems to work _everywhere_ except on hints.

Ah I see the XML control example I entered also got edited out, didn't see it.

Edit: re-added the XML example

**Comment by Genhis** [comment]
What is the value for `menu.1528` key? I guess it may contain characters which `replaceAll()` treats as regex groups.

When you use this key in a regular text, do you still get the error?

    <text style="base-font" text="${menu.1528}" />

**Comment by tonihele** [comment]
The value is 
> 麌黷麌麸麌點麋0麌鼬麋$

Anything with a dollar sign will cause the crash. That is how Java's regex work. For regular text attributes these seem to be fine. I didn't debug, but my guess that the text doesn't go to this particular class for processing.
