### ISSUE TITLE
Crash-To-Desktop from Nifty Text Control

### ISSUE THREAD

**Issue by zerosep** [nifty-gui/nifty-gui#97]
If you copy text containing newlines (for example \n123\n) into a text field control and then try to select text (for example shift then left arrow) nifty crashes with the following stack trace:

ErrMsg: Uncaught exception thrown in Thread[LWJGL Renderer Thread,5,main]
Exception: java.lang.StringIndexOutOfBoundsException: String index out of range: 14
at java.lang.String.substring(Unknown Source)
at
de.lessvoid.nifty.render.NiftyRenderEngineImpl.renderSelectionText(NiftyRenderEngineImpl.java:323)
at de.lessvoid.nifty.render.NiftyRenderEngineImpl.renderText(NiftyRenderEngineImpl.java:266)
at de.lessvoid.nifty.elements.render.TextRenderer.renderLine(TextRenderer.java:302)
at de.lessvoid.nifty.elements.render.TextRenderer.renderLines(TextRenderer.java:201)
at de.lessvoid.nifty.elements.render.TextRenderer.render(TextRenderer.java:182)
at de.lessvoid.nifty.elements.Element.renderElement(Element.java:734)
at de.lessvoid.nifty.elements.Element.render(Element.java:719)
at de.lessvoid.nifty.elements.Element.renderInternalChildElements(Element.java:751)
at de.lessvoid.nifty.elements.Element.renderChildren(Element.java:741)
at de.lessvoid.nifty.elements.Element.render(Element.java:722)
at de.lessvoid.nifty.elements.Element.renderInternalChildElements(Element.java:751)
at de.lessvoid.nifty.elements.Element.renderChildren(Element.java:744)
at de.lessvoid.nifty.elements.Element.render(Element.java:722)
at de.lessvoid.nifty.elements.Element.renderInternalChildElements(Element.java:751)
at de.lessvoid.nifty.elements.Element.renderChildren(Element.java:744)
at de.lessvoid.nifty.elements.Element.render(Element.java:713)
at de.lessvoid.nifty.elements.Element.renderInternalChildElements(Element.java:751)
at de.lessvoid.nifty.elements.Element.renderChildren(Element.java:744)
at de.lessvoid.nifty.elements.Element.render(Element.java:713)
at de.lessvoid.nifty.elements.Element.renderInternalChildElements(Element.java:751)
at de.lessvoid.nifty.elements.Element.renderChildren(Element.java:744)
at de.lessvoid.nifty.elements.Element.render(Element.java:722)
at de.lessvoid.nifty.elements.Element.renderInternalChildElements(Element.java:751)
at de.lessvoid.nifty.elements.Element.renderChildren(Element.java:744)
at de.lessvoid.nifty.elements.Element.render(Element.java:713)
at de.lessvoid.nifty.screen.Screen.renderLayers(Screen.java:314)
at de.lessvoid.nifty.Nifty.render(Nifty.java:321)
at com.jme3.niftygui.NiftyJmeDisplay.postQueue(NiftyJmeDisplay.java:178)
at com.jme3.renderer.RenderManager.renderViewPort(RenderManager.java:979)
at com.jme3.renderer.RenderManager.render(RenderManager.java:1035)
at com.jme3.app.SimpleApplication.update(SimpleApplication.java:252)
at com.jme3.system.lwjgl.LwjglAbstractDisplay.runLoop(LwjglAbstractDisplay.java:151)
at com.jme3.system.lwjgl.LwjglDisplay.runLoop(LwjglDisplay.java:185)
at com.jme3.system.lwjgl.LwjglAbstractDisplay.run(LwjglAbstractDisplay.java:228)
at java.lang.Thread.run(Unknown Source)

For now as a work-around I’ve attached a filter to all the controls where it’s likely to happen, I had a look in the text field control code itself and wasn’t sure where the best place to fix it was, although the most likely place I saw was in

private boolean filterAndInsert(final CharSequence chars) {

My work-around filter is as simple as this:

 private final TextFieldInputCharFilter textFieldFilter = new TextFieldInputCharFilter() {

```
    public boolean acceptInput(int i, char c) {
        return c != ‘\n’ && c != ‘\r’;
    }
};
```

Although I have to manually apply that to every text field.

It seems to me two separate fixes are needed here, one to prevent the crash on selection if newline is present and then another to prevent newlines being pasted into a text field control in the first place...

**Comment by zerosep** [comment]
Original thread on the jme forums:
http://jmonkeyengine.org/forum/topic/crash-inside-nifty-renderelement/#post-204690
